In [3]:
import polars as pl
import polars.selectors as cs

In [ ]:
pl.read_parquet('data/yellow_tripdata_2026-04.parquet')

shape: (3_831_240, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 25.6      ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:40:05  ┆ 00:52:44  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 54.19     ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:09:19  ┆ 00:21:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 46.2      ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:15:29  ┆ 00:34:14  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 0         ┆ … ┆ 60.55     ┆ 2.5       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:14:20  ┆ 00:27:49  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 17.22     ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:04:53  ┆ 00:11:54  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2026-04-3 ┆ 2026-04-3 ┆ null      ┆ … ┆ 22.16     ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:02:00  ┆ 23:08:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-04-3 ┆ null      ┆ … ┆ 47.31     ┆ null      ┆ null      ┆ 0.75      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:08:31  ┆ 23:33:16  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-04-3 ┆ null      ┆ … ┆ 22.1      ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:10:19  ┆ 23:31:11  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-05-0 ┆ null      ┆ … ┆ 35.16     ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 0         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:46:47  ┆ 00:07:22  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-05-0 ┆ null      ┆ … ┆ 58.0      ┆ null      ┆ null      ┆ 0.75      │
│          ┆ 0         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:58:15  ┆ 00:25:54  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
data = pl.read_parquet('data/yellow_tripdata_2026-04.parquet')
data

shape: (3_831_240, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 25.6      ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:40:05  ┆ 00:52:44  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 54.19     ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:09:19  ┆ 00:21:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 46.2      ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:15:29  ┆ 00:34:14  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 0         ┆ … ┆ 60.55     ┆ 2.5       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:14:20  ┆ 00:27:49  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 17.22     ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:04:53  ┆ 00:11:54  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2026-04-3 ┆ 2026-04-3 ┆ null      ┆ … ┆ 22.16     ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:02:00  ┆ 23:08:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-04-3 ┆ null      ┆ … ┆ 47.31     ┆ null      ┆ null      ┆ 0.75      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:08:31  ┆ 23:33:16  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-04-3 ┆ null      ┆ … ┆ 22.1      ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:10:19  ┆ 23:31:11  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-05-0 ┆ null      ┆ … ┆ 35.16     ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 0         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:46:47  ┆ 00:07:22  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ 2026-05-0 ┆ null      ┆ … ┆ 58.0      ┆ null      ┆ null      ┆ 0.75      │
│          ┆ 0         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:58:15  ┆ 00:25:54  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
#Lazy mode
data = pl.scan_parquet('data/yellow_tripdata_2026-04.parquet')
data.head(7)

In [11]:
#Lazy mode
data = pl.scan_parquet('data/yellow_tripdata_2026-04.parquet')
data.head(7).collect()

shape: (7, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 25.6      ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:40:05  ┆ 00:52:44  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 54.19     ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:09:19  ┆ 00:21:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 46.2      ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:15:29  ┆ 00:34:14  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 0         ┆ … ┆ 60.55     ┆ 2.5       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:14:20  ┆ 00:27:49  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 17.22     ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:04:53  ┆ 00:11:54  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 7        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 2         ┆ … ┆ 14.3      ┆ 2.5       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:10:12  ┆ 00:10:12  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 2026-04-0 ┆ 1         ┆ … ┆ 21.38     ┆ 2.5       ┆ 0.0       ┆ 0.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:37:00  ┆ 00:45:17  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
data.select(

#pl.col('VendorID','tpep_pickup_datetime')#.show_graph() -ne march pas
pl.all()
, (pl.col('trip_distance')/pl.col('passenger_count')).alias('dustance_per_passenger') 
)

In [25]:
data.select(

pl.exclude('trip_distance','passenger_count') 
, (pl.col('trip_distance')/pl.col('passenger_count')).alias('dustance_per_passenger') 
)

In [42]:
data.select(
    pl.col(pl.Int32)
    , pl.col('tpep_pickup_datetime')
)

data.select(
    cs.contains('datetime')
    , cs.starts_with
    , cs.ends_with
    ).collect()

TypeError: cannot create expression literal for value of type function.

Hint: Pass `allow_object=True` to accept any value and create a literal of type Object.

In [38]:
data.select(
    pl.exclude('tpep_dropoff_datetime')
).filter(
    (pl.col('trip_distance') >= 50)
    & (pl.col('trip_distance') < 80)
)#.show_graph()

In [41]:
data.select(
    pl.exclude('tpep_dropoff_datetime')
).filter(
    (pl.col('trip_distance') >= 50)
    & (pl.col('trip_distance') < 80)
    | pl.col('VendorID').is_in((2,7))
)#.show_graph()

In [43]:
data.select(
    pl.exclude('tpep_dropoff_datetime')
).filter(
    (pl.col('trip_distance') >= 50)
    & (pl.col('trip_distance') < 80)
    | ~(pl.col('VendorID').is_in((2,7)))
)#.show_graph()

In [46]:
data.select(
    pl.exclude('tpep_dropoff_datetime')
).filter(
   pl.col('trip_distance').is_between(50,80)
   , pl.col('trip_distance').eq(50) 
   , pl.col('store_and_fwd_flag').str.contains('N')
)#.show_graph()

In [47]:
data.select(
    pl.exclude('tpep_dropoff_datetime')
).filter(
   pl.col('trip_distance').is_between(50,80)
   
).collect()

shape: (479, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ passenger ┆ trip_dist ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ _count    ┆ ance      ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ i32      ┆ me        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ i64       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2026-04-0 ┆ 3         ┆ 55.72     ┆ … ┆ 443.36    ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 06:55:10  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 1         ┆ 61.28     ┆ … ┆ 356.69    ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 06:41:42  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-0 ┆ 1         ┆ 62.1      ┆ … ┆ 32.0      ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:36:15  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 1         ┆ 58.21     ┆ … ┆ 440.36    ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:40:56  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-0 ┆ 0         ┆ 52.6      ┆ … ┆ 318.46    ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 09:04:57  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2026-04-2 ┆ null      ┆ 54.99     ┆ … ┆ 181.51    ┆ null      ┆ null      ┆ 0.75      │
│          ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 06:52:46  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-2 ┆ null      ┆ 53.9      ┆ … ┆ 211.93    ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 12:09:06  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-2 ┆ null      ┆ 73.4      ┆ … ┆ 49.32     ┆ null      ┆ null      ┆ 0.75      │
│          ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:54:19  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-3 ┆ null      ┆ 77.8      ┆ … ┆ 45.07     ┆ null      ┆ null      ┆ 0.0       │
│          ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:42:24  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-3 ┆ null      ┆ 50.28     ┆ … ┆ 196.84    ┆ null      ┆ null      ┆ 0.75      │
│          ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 09:25:06  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [57]:
data.select(
    pl.exclude('tpep_dropoff_datetime')
).filter(
   pl.col('trip_distance').is_between(50,80)
   
).cast(
    {
        'trip_distance': pl.Float32
        ,'total_amount': pl.Decimal(18,2)
        ,'passenger_count': pl.UInt8
        }
).head(5).collect()

shape: (5, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ passenger ┆ trip_dist ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ _count    ┆ ance      ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ i32      ┆ me        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ u8        ┆ f32       ┆   ┆ decimal[1 ┆ ---       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆           ┆           ┆   ┆ 8,2]      ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2026-04-0 ┆ 3         ┆ 55.720001 ┆ … ┆ 443.36    ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 06:55:10  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 1         ┆ 61.279999 ┆ … ┆ 356.69    ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 06:41:42  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-0 ┆ 1         ┆ 62.099998 ┆ … ┆ 32.00     ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:36:15  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2026-04-0 ┆ 1         ┆ 58.209999 ┆ … ┆ 440.36    ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:40:56  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2026-04-0 ┆ 0         ┆ 52.599998 ┆ … ┆ 318.46    ┆ 0.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 09:04:57  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [55]:

0.1+0.2
data.schema

C:\Users\stgadmin\AppData\Local\Temp\ipykernel_3944\3865673242.py:2: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  data.schema

Schema([('VendorID', Int32),
        ('tpep_pickup_datetime', Datetime(time_unit='us', time_zone=None)),
        ('tpep_dropoff_datetime', Datetime(time_unit='us', time_zone=None)),
        ('passenger_count', Int64),
        ('trip_distance', Float64),
        ('RatecodeID', Int64),
        ('store_and_fwd_flag', String),
        ('PULocationID', Int32),
        ('DOLocationID', Int32),
        ('payment_type', Int64),
        ('fare_amount', Float64),
        ('extra', Float64),
        ('mta_tax', Float64),
        ('tip_amount', Float64),
        ('tolls_amount', Float64),
        ('improvement_surcharge', Float64),
        ('total_amount', Float64),
        ('congestion_surcharge', Float64),
        ('Airport_fee', Float64),
        ('cbd_congestion_fee', Float64)])

In [59]:
data.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ VendorID  ┆ tpep_pick ┆ tpep_drop ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_cong │
│ ---       ┆ ---       ┆ up_dateti ┆ off_datet ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ estion_f │
│ str       ┆ f64       ┆ me        ┆ ime       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ee       │
│           ┆           ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.83124e6 ┆ 3831240   ┆ 3831240   ┆ … ┆ 3.83124e6 ┆ 3.031454e ┆ 3.031454e ┆ 3.83124e │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 6         ┆ 6        │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 799786.0  ┆ 799786.0  ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.875816  ┆ 2026-04-1 ┆ 2026-04-1 ┆ … ┆ 30.000362 ┆ 2.195815  ┆ 0.164319  ┆ 0.532881 │
│           ┆           ┆ 6 11:30:0 ┆ 6 11:48:1 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9.550314  ┆ 0.193474  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 0.738918  ┆ null      ┆ null      ┆ … ┆ 22.117126 ┆ 0.846796  ┆ 0.577581  ┆ 0.344308 │
│ min       ┆ 1.0       ┆ 2001-01-0 ┆ 2001-01-0 ┆ … ┆ -1278.4   ┆ -2.5      ┆ -2.0      ┆ -0.75    │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 09:23:58  ┆ 16:09:38  ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 2.0       ┆ 2026-04-0 ┆ 2026-04-0 ┆ … ┆ 17.35     ┆ 2.5       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:30:49  ┆ 10:49:34  ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2.0       ┆ 2026-04-1 ┆ 2026-04-1 ┆ … ┆ 23.58     ┆ 2.5       ┆ 0.0       ┆ 0.75     │
│           ┆           ┆ 6         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 17:40:48  ┆ 18:01:13  ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.0       ┆ 2026-04-2 ┆ 2026-04-2 ┆ … ┆ 34.46     ┆ 2.5       ┆ 0.0       ┆ 0.75     │
│           ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 19:30:30  ┆ 19:48:41  ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 7.0       ┆ 2026-05-0 ┆ 2026-05-0 ┆ … ┆ 1452.66   ┆ 2.5       ┆ 27.0      ┆ 0.75     │
│           ┆           ┆ 1         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 00:01:28  ┆ 12:06:09  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [63]:
data.with_columns(
    my_col = pl.col('VendorID')
)

In [66]:
(
data.with_columns(
    trip_category = pl.when(pl.col('trip_distance') < 0).then(pl.lit('anomalies'))
    .when(pl.col('trip_distance').is_between(0,5)).then(pl.lit('small trip'))
    .otherwise(pl.lit('big trip')))
.select(pl.col('trip_category'))
)

In [70]:
(
data
    .select(pl.col('trip_distance'))\
    .with_columns(
    trip_category = pl.when(pl.col('trip_distance') < 0).then(pl.lit('anomalies'))
    .when(pl.col('trip_distance').is_between(0,5)).then(pl.lit('small trip'))
    .otherwise(pl.lit('big trip')))
.select(pl.col('trip_category'))
).collect()

shape: (3_831_240, 1)
┌───────────────┐
│ trip_category │
│ ---           │
│ str           │
╞═══════════════╡
│ small trip    │
│ big trip      │
│ big trip      │
│ big trip      │
│ small trip    │
│ …             │
│ small trip    │
│ big trip      │
│ small trip    │
│ small trip    │
│ big trip      │
└───────────────┘