# Exercices Polars

La série suivante d'exercices doit vous permettre de maîtriser les rudiments de Polars. Elle présupose que vous ayez déjà les bases avec Pandas et SQL.

Toutes les fonctions et méthodes nécessaires à cette série n'ont bien évidemment été pas abordées durant la session théorique et ces exercices vous forceront à trouver des pistes de solution dans la [documentation](https://www.pola.rs/) officielle.

Soyez curieux et n'hésitez pas à aller plus loin que les énoncés et à analyser plus en profondeur le dataset proposé.

**Conseil:** Si des exercices vous résistent, fragmentez votre problème en petits morceaux. N'hésitez pas à lister les différentes étapes nécessaire à l'élaboration des exercices avant de vous lancer dans le code.

<br>

#### 1 Procurez-vous le fichier [ici](https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i) et affichez les 5 premières lignes

**Conseil:** avant d'aller plus loin, prenez le temps de lire les informations présentes afin de bien comprendre les données avec lesquelles vous travaillerez.

<br>

In [15]:
import polars as pl
import polars.selectors as cs
import os
os.getcwd()
#pl.read_parquet("data/data_exo/data/NYPD_complaints_all.parquet")

'c:\\Users\\stgadmin\\AI-Specialist\\Polars-training'

In [16]:
data_csv = pl.read_csv("data/data_exo/data/NYPD_complaints_all.csv")
data_csv.head(3)

shape: (3, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ (null)    ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ (null)    ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [17]:
data_parquet = pl.read_parquet("data/data_exo/data/NYPD_complaints_all.parquet")


data_parquet.head(3)

shape: (3, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ (null)    ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ (null)    ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 2 Affichez le nombre de lignes, de colonnes, le schéma ainsi que le poids total du fichier en mémoire

<br>

In [ ]:
data = pl.read_csv("data/data_exo/data/NYPD_complaints_all.csv")

# This block displays the number of rows and columns.
print("Nombre de lignes :", data.height)
print("Nombre de colonnes :", data.width)
print("Shape :", data.shape)
# This block displays the schema: column names and data types.
print("Schéma :")
print(data.schema)
# This block displays the estimated memory size of the DataFrame.
print("Poids mémoire :", data.estimated_size("mb"), "MB")

Nombre de lignes : 8353049
Nombre de colonnes : 35
Shape : (8353049, 35)
Schéma :
Schema({'CMPLNT_NUM': String, 'CMPLNT_FR_DT': String, 'CMPLNT_FR_TM': String, 'CMPLNT_TO_DT': String, 'CMPLNT_TO_TM': String, 'ADDR_PCT_CD': Int64, 'RPT_DT': String, 'KY_CD': Int64, 'OFNS_DESC': String, 'PD_CD': Int64, 'PD_DESC': String, 'CRM_ATPT_CPTD_CD': String, 'LAW_CAT_CD': String, 'BORO_NM': String, 'LOC_OF_OCCUR_DESC': String, 'PREM_TYP_DESC': String, 'JURIS_DESC': String, 'JURISDICTION_CODE': Int64, 'PARKS_NM': String, 'HADEVELOPT': String, 'HOUSING_PSA': String, 'X_COORD_CD': Int64, 'Y_COORD_CD': Int64, 'SUSP_AGE_GROUP': String, 'SUSP_RACE': String, 'SUSP_SEX': String, 'TRANSIT_DISTRICT': String, 'Latitude': Float64, 'Longitude': Float64, 'Lat_Lon': String, 'PATROL_BORO': String, 'STATION_NAME': String, 'VIC_AGE_GROUP': String, 'VIC_RACE': String, 'VIC_SEX': String})
Poids mémoire : 2669.508087158203 MB

In [26]:
data = pl.scan_csv("data/data_exo/data/NYPD_complaints_all.csv")
# This block displays the schema of a LazyFrame without collecting the full table.
print("Schéma :")
print(data.collect_schema())
# This block executes the LazyFrame and loads the result into memory as a DataFrame.

df = data.collect()

# This block displays rows, columns, schema, and estimated memory size.
print("Nombre de lignes :", df.height)
print("Nombre de colonnes :", df.width)
print("Shape :", df.shape)

print("Schéma :")
print(df.schema)

print("Poids mémoire :", df.estimated_size("mb"), "MB")
data.limit(3).collect()

Schéma :
Schema({'CMPLNT_NUM': String, 'CMPLNT_FR_DT': String, 'CMPLNT_FR_TM': String, 'CMPLNT_TO_DT': String, 'CMPLNT_TO_TM': String, 'ADDR_PCT_CD': Int64, 'RPT_DT': String, 'KY_CD': Int64, 'OFNS_DESC': String, 'PD_CD': Int64, 'PD_DESC': String, 'CRM_ATPT_CPTD_CD': String, 'LAW_CAT_CD': String, 'BORO_NM': String, 'LOC_OF_OCCUR_DESC': String, 'PREM_TYP_DESC': String, 'JURIS_DESC': String, 'JURISDICTION_CODE': Int64, 'PARKS_NM': String, 'HADEVELOPT': String, 'HOUSING_PSA': String, 'X_COORD_CD': Int64, 'Y_COORD_CD': Int64, 'SUSP_AGE_GROUP': String, 'SUSP_RACE': String, 'SUSP_SEX': String, 'TRANSIT_DISTRICT': String, 'Latitude': Float64, 'Longitude': Float64, 'Lat_Lon': String, 'PATROL_BORO': String, 'STATION_NAME': String, 'VIC_AGE_GROUP': String, 'VIC_RACE': String, 'VIC_SEX': String})
Nombre de lignes : 8353049
Nombre de colonnes : 35
Shape : (8353049, 35)
Schéma :
Schema({'CMPLNT_NUM': String, 'CMPLNT_FR_DT': String, 'CMPLNT_FR_TM': String, 'CMPLNT_TO_DT': String, 'CMPLNT_TO_TM': String, 'ADDR_PCT_CD': Int64, 'RPT_DT': String, 'KY_CD': Int64, 'OFNS_DESC': String, 'PD_CD': Int64, 'PD_DESC': String, 'CRM_ATPT_CPTD_CD': String, 'LAW_CAT_CD': String, 'BORO_NM': String, 'LOC_OF_OCCUR_DESC': String, 'PREM_TYP_DESC': String, 'JURIS_DESC': String, 'JURISDICTION_CODE': Int64, 'PARKS_NM': String, 'HADEVELOPT': String, 'HOUSING_PSA': String, 'X_COORD_CD': Int64, 'Y_COORD_CD': Int64, 'SUSP_AGE_GROUP': String, 'SUSP_RACE': String, 'SUSP_SEX': String, 'TRANSIT_DISTRICT': String, 'Latitude': Float64, 'Longitude': Float64, 'Lat_Lon': String, 'PATROL_BORO': String, 'STATION_NAME': String, 'VIC_AGE_GROUP': String, 'VIC_RACE': String, 'VIC_SEX': String})
Poids mémoire : 2669.2869243621826 MB

shape: (3, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ (null)    ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ (null)    ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [6]:
# This block imports Polars and scans the CSV lazily.
import polars as pl
# This block collects the LazyFrame into a DataFrame so we can measure rows, columns, and memory size.
df = data
# data = pl.scan_csv("data\data_exo\data\NYPD_complaints_all.csv")
# This block prints the requested information: rows, columns, schema, and memory size.
print("Nombre de lignes :", df.height)
print("Nombre de colonnes :", df.width)
print("Shape :", df.shape)

print(r"\nSchéma :")
print(df.schema)

print(r"\nPoids mémoire estimé :", round(df.estimated_size("mb"), 2), "MB")

Nombre de lignes : 8353049
Nombre de colonnes : 35
Shape : (8353049, 35)
\nSchéma :
Schema({'CMPLNT_NUM': String, 'CMPLNT_FR_DT': String, 'CMPLNT_FR_TM': String, 'CMPLNT_TO_DT': String, 'CMPLNT_TO_TM': String, 'ADDR_PCT_CD': Int64, 'RPT_DT': String, 'KY_CD': Int64, 'OFNS_DESC': String, 'PD_CD': Int64, 'PD_DESC': String, 'CRM_ATPT_CPTD_CD': String, 'LAW_CAT_CD': String, 'BORO_NM': String, 'LOC_OF_OCCUR_DESC': String, 'PREM_TYP_DESC': String, 'JURIS_DESC': String, 'JURISDICTION_CODE': Int64, 'PARKS_NM': String, 'HADEVELOPT': String, 'HOUSING_PSA': String, 'X_COORD_CD': Int64, 'Y_COORD_CD': Int64, 'SUSP_AGE_GROUP': String, 'SUSP_RACE': String, 'SUSP_SEX': String, 'TRANSIT_DISTRICT': String, 'Latitude': Float64, 'Longitude': Float64, 'Lat_Lon': String, 'PATROL_BORO': String, 'STATION_NAME': String, 'VIC_AGE_GROUP': String, 'VIC_RACE': String, 'VIC_SEX': String})
\nPoids mémoire estimé : 2669.51 MB

#### 3 Affichez le nombre et la proportion de valeurs manquantes par colonne et pour le dataset au complet

<br>

In [ ]:
import polars as pl

# This block gets the number of rows in the Polars DataFrame.

n_rows = df.height
missing_table = (
    df.null_count()
    .transpose(
        include_header=True,
        header_name="column",
        column_names=["missing_count"]
    )
    .with_columns(
        (pl.col("missing_count") / n_rows * 100)
        .round(2)
        .alias("missing_percent")
    )
    .sort("missing_percent", descending=True)
)

missing_table
#df.null_count()

df_lazy=data_lazy.collect()

shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 0         ┆ 1778361   ┆ … ┆ 0         ┆ 0         ┆ 0        ┆ 0       │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [45]:
data_lazy = pl.scan_csv("data/data_exo/data/NYPD_complaints_all.csv")
df_lazy=data_lazy.collect()

n_rows = df_lazy.height
print(n_rows)
print(df_lazy.null_count())
# This block counts missing/null values for each column without transposing.
missing_count = df_lazy.null_count()
missing_count
missing_percent = missing_count.select(
    (pl.all() / df_lazy.height * 100).round(2)
)

print(missing_percent)

print('/ntransposed')

#transposed
missing_table = (
    df_lazy.null_count()
    .transpose(
        include_header=True,
        header_name="column",
        column_names=["missing_count"]
    )
    .with_columns(
        (pl.col("missing_count") / n_rows * 100)
        .round(2)
        .alias("missing_percent")
    )
    .sort("missing_percent", descending=True)
)

missing_table

8353049
shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 0         ┆ 1778361   ┆ … ┆ 0         ┆ 0         ┆ 0        ┆ 0       │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘
shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ f64        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│            ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0.0        ┆ 0.01       ┆ 0.0       ┆ 21.29     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0      ┆ 0.0     │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘
/ntransposed

shape: (35, 3)
┌──────────────────┬───────────────┬─────────────────┐
│ column           ┆ missing_count ┆ missing_percent │
│ ---              ┆ ---           ┆ ---             │
│ str              ┆ u32           ┆ f64             │
╞══════════════════╪═══════════════╪═════════════════╡
│ TRANSIT_DISTRICT ┆ 8169741       ┆ 97.81           │
│ CMPLNT_TO_DT     ┆ 1778361       ┆ 21.29           │
│ PD_CD            ┆ 1780          ┆ 0.02            │
│ CMPLNT_FR_DT     ┆ 655           ┆ 0.01            │
│ CMPLNT_NUM       ┆ 0             ┆ 0.0             │
│ …                ┆ …             ┆ …               │
│ PATROL_BORO      ┆ 0             ┆ 0.0             │
│ STATION_NAME     ┆ 0             ┆ 0.0             │
│ VIC_AGE_GROUP    ┆ 0             ┆ 0.0             │
│ VIC_RACE         ┆ 0             ┆ 0.0             │
│ VIC_SEX          ┆ 0             ┆ 0.0             │
└──────────────────┴───────────────┴─────────────────┘

#### 4 Pour vous simplifier la vie avec le reste des exercices, mettez en minuscule le nom des colonnes

#### 4.1 Pensez également à convertir les colonnes qui devraient être en DateTime et éventuellement à regrouper les parties Date et Time

#### 4.2 Retirez les colonnes 'cmplnt_fr_tm' et 'cmplnt_to_tm' puisque vous avez tout regroupé dans une seule et même colonne

<br>

In [48]:
df = data.collect()
# df.with_columns(pl.all().name.to_lowercase())
df = df.rename(lambda column_name: column_name.lower())
print(df.schema)
df.head(3)

Schema({'cmplnt_num': String, 'cmplnt_fr_dt': String, 'cmplnt_fr_tm': String, 'cmplnt_to_dt': String, 'cmplnt_to_tm': String, 'addr_pct_cd': Int64, 'rpt_dt': String, 'ky_cd': Int64, 'ofns_desc': String, 'pd_cd': Int64, 'pd_desc': String, 'crm_atpt_cptd_cd': String, 'law_cat_cd': String, 'boro_nm': String, 'loc_of_occur_desc': String, 'prem_typ_desc': String, 'juris_desc': String, 'jurisdiction_code': Int64, 'parks_nm': String, 'hadevelopt': String, 'housing_psa': String, 'x_coord_cd': Int64, 'y_coord_cd': Int64, 'susp_age_group': String, 'susp_race': String, 'susp_sex': String, 'transit_district': String, 'latitude': Float64, 'longitude': Float64, 'lat_lon': String, 'patrol_boro': String, 'station_name': String, 'vic_age_group': String, 'vic_race': String, 'vic_sex': String})

shape: (3, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_fr ┆ cmplnt_to ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _tm       ┆ _dt       ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ (null)    ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ (null)    ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [63]:
# This block combines complaint start date + time, complaint end date + time,
# and converts the report date into a real Date column.
data_new_time = df.with_columns(
    pl.concat_str(
        [pl.col("cmplnt_fr_dt"), pl.col("cmplnt_fr_tm")],
        separator=" ",
        ignore_nulls=False
    )
    .str.strptime(pl.Datetime, format=r"%m/%d/%Y %H:%M:%S", strict=False)
    .alias("cmplnt_fr_datetime"),

    pl.concat_str(
        [pl.col("cmplnt_to_dt"), pl.col("cmplnt_to_tm")],
        separator=" ",
        ignore_nulls=False
    )
    .str.strptime(pl.Datetime, format=r"%m/%d/%Y %H:%M:%S", strict=False)
    .alias("cmplnt_to_datetime"),

    pl.col("rpt_dt")
    .str.strptime(pl.Date, format=r"%m/%d/%Y", strict=False)
    .alias("rpt_date")
)

# This block verifies the new datetime/date columns.
print(data_new_time.select(
    "cmplnt_fr_dt",
    "cmplnt_fr_tm",
    "cmplnt_fr_datetime",
    "cmplnt_to_dt",
    "cmplnt_to_tm",
    "cmplnt_to_datetime",
    "rpt_dt",
    "rpt_date"
).head(2))


print(data_new_time.head(5))


# This block removes the two time columns because they were already combined into datetime columns.
data_new_time_less = data_new_time.drop(["cmplnt_fr_tm", "cmplnt_to_tm", "cmplnt_fr_dt", "cmplnt_to_dt"])

print(data_new_time_less.head(3))

shape: (2, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ cmplnt_fr_ ┆ cmplnt_fr_ ┆ cmplnt_fr_ ┆ cmplnt_to ┆ cmplnt_to ┆ cmplnt_to ┆ rpt_dt    ┆ rpt_date  │
│ dt         ┆ tm         ┆ datetime   ┆ _dt       ┆ _tm       ┆ _datetime ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ str       ┆ date      │
│ str        ┆ str        ┆ datetime[μ ┆ str       ┆ str       ┆ datetime[ ┆           ┆           │
│            ┆            ┆ s]         ┆           ┆           ┆ μs]       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 01/01/2002 ┆ 11:00:00   ┆ 2002-01-01 ┆ 02/25/200 ┆ 11:00:00  ┆ 2006-02-2 ┆ 03/06/200 ┆ 2006-03-0 │
│            ┆            ┆ 11:00:00   ┆ 6         ┆           ┆ 5         ┆ 6         ┆ 6         │
│            ┆            ┆            ┆           ┆           ┆ 11:00:00  ┆           ┆           │
│ 04/22/2005 ┆ 02:00:00   ┆ 2005-04-22 ┆ null      ┆ (null)    ┆ null      ┆ 04/22/200 ┆ 2006-04-2 │
│            ┆            ┆ 02:00:00   ┆           ┆           ┆           ┆ 6         ┆ 2         │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (5, 38)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ cmplnt_num ┆ cmplnt_fr ┆ cmplnt_fr ┆ cmplnt_to ┆ … ┆ vic_sex ┆ cmplnt_fr ┆ cmplnt_to ┆ rpt_date  │
│ ---        ┆ _dt       ┆ _tm       ┆ _dt       ┆   ┆ ---     ┆ _datetime ┆ _datetime ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str     ┆ ---       ┆ ---       ┆ date      │
│            ┆ str       ┆ str       ┆ str       ┆   ┆         ┆ datetime[ ┆ datetime[ ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆ μs]       ┆ μs]       ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 10600119   ┆ 01/01/200 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ F       ┆ 2002-01-0 ┆ 2006-02-2 ┆ 2006-03-0 │
│            ┆ 2         ┆           ┆ 6         ┆   ┆         ┆ 1         ┆ 5         ┆ 6         │
│            ┆           ┆           ┆           ┆   ┆         ┆ 11:00:00  ┆ 11:00:00  ┆           │
│ 11052575   ┆ 04/22/200 ┆ 02:00:00  ┆ null      ┆ … ┆ M       ┆ 2005-04-2 ┆ null      ┆ 2006-04-2 │
│            ┆ 5         ┆           ┆           ┆   ┆         ┆ 2         ┆           ┆ 2         │
│            ┆           ┆           ┆           ┆   ┆         ┆ 02:00:00  ┆           ┆           │
│ 10832306   ┆ 07/11/200 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ M       ┆ 2005-07-1 ┆ 2006-03-2 ┆ 2006-03-2 │
│            ┆ 5         ┆           ┆ 6         ┆   ┆         ┆ 1         ┆ 9         ┆ 9         │
│            ┆           ┆           ┆           ┆   ┆         ┆ 20:00:00  ┆ 12:00:00  ┆           │
│ 10107192   ┆ 10/19/200 ┆ 20:30:00  ┆ null      ┆ … ┆ F       ┆ 2005-10-1 ┆ null      ┆ 2006-01-1 │
│            ┆ 5         ┆           ┆           ┆   ┆         ┆ 9         ┆           ┆ 3         │
│            ┆           ┆           ┆           ┆   ┆         ┆ 20:30:00  ┆           ┆           │
│ 23893731   ┆ 12/04/200 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ F       ┆ 2005-12-0 ┆ 2006-08-0 ┆ 2006-08-0 │
│            ┆ 5         ┆           ┆ 6         ┆   ┆         ┆ 4         ┆ 9         ┆ 9         │
│            ┆           ┆           ┆           ┆   ┆         ┆ 09:00:00  ┆ 17:00:00  ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘
shape: (3, 34)
┌────────────┬────────────┬────────────┬───────┬───┬─────────┬────────────┬────────────┬───────────┐
│ cmplnt_num ┆ addr_pct_c ┆ rpt_dt     ┆ ky_cd ┆ … ┆ vic_sex ┆ cmplnt_fr_ ┆ cmplnt_to_ ┆ rpt_date  │
│ ---        ┆ d          ┆ ---        ┆ ---   ┆   ┆ ---     ┆ datetime   ┆ datetime   ┆ ---       │
│ str        ┆ ---        ┆ str        ┆ i64   ┆   ┆ str     ┆ ---        ┆ ---        ┆ date      │
│            ┆ i64        ┆            ┆       ┆   ┆         ┆ datetime[μ ┆ datetime[μ ┆           │
│            ┆            ┆            ┆       ┆   ┆         ┆ s]         ┆ s]         ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═════════╪════════════╪════════════╪═══════════╡
│ 10600119   ┆ null       ┆ 03/06/2006 ┆ 104   ┆ … ┆ F       ┆ 2002-01-01 ┆ 2006-02-25 ┆ 2006-03-0 │
│            ┆            ┆            ┆       ┆   ┆         ┆ 11:00:00   ┆ 11:00:00   ┆ 6         │
│ 11052575   ┆ null       ┆ 04/22/2006 ┆ 110   ┆ … ┆ M       ┆ 2005-04-22 ┆ null       ┆ 2006-04-2 │
│            ┆            ┆            ┆       ┆   ┆         ┆ 02:00:00   ┆            ┆ 2         │
│ 10832306   ┆ null       ┆ 03/29/2006 ┆ 353   ┆ … ┆ M       ┆ 2005-07-11 ┆ 2006-03-29 ┆ 2006-03-2 │
│            ┆            ┆            ┆       ┆   ┆         ┆ 20:00:00   ┆ 12:00:00   ┆ 9         │
└────────────┴────────────┴────────────┴───────┴───┴─────────┴────────────┴────────────┴───────────┘

#### 5 Vérifiez si les colonnes en Int64 peuvent être converties en Int32 afin de gagner en espace mémoire

<br>

In [91]:
# This block defines the Int32 limits and reads the current LazyFrame schema.
INT32_MIN = -2_147_483_648
INT32_MAX = 2_147_483_647

schema = df.collect_schema()

int64_cols = [
    column_name
    for column_name, dtype in schema.items()
    if dtype == pl.Int64
]

print("Colonnes Int64 trouvées :", int64_cols)


# This block checks whether Int64 columns exist.
# If yes, it verifies whether they can safely be converted to Int32.
# If no, it skips the conversion without crashing.
if len(int64_cols) == 0:
    print("Aucune colonne Int64 trouvée. Rien à convertir.")

    int64_check = pl.DataFrame({
        "column": pl.Series([], dtype=pl.String),
        "min_value": pl.Series([], dtype=pl.Int64),
        "max_value": pl.Series([], dtype=pl.Int64),
        "can_cast_to_int32": pl.Series([], dtype=pl.Boolean),
    })

    cols_to_cast = []

else:
    stats_wide = df.select(
        *[pl.col(col).min().alias(f"{col}__min") for col in int64_cols],
        *[pl.col(col).max().alias(f"{col}__max") for col in int64_cols],
    )
    stats_row = stats_wide.row(0, named=True)

    int64_check = pl.DataFrame({
        "column": int64_cols,
        "min_value": [stats_row[f"{col}__min"] for col in int64_cols],
        "max_value": [stats_row[f"{col}__max"] for col in int64_cols],
    }).with_columns(
        (
            (pl.col("min_value") >= INT32_MIN)
            & (pl.col("max_value") <= INT32_MAX)
        ).alias("can_cast_to_int32")
    )

    cols_to_cast = (
        int64_check
        .filter(pl.col("can_cast_to_int32"))
        .get_column("column")
        .to_list()
    )

print(int64_check)
print("Colonnes à convertir :", cols_to_cast)

# This block converts only the compatible Int64 columns into Int32.
# If there are no columns to convert, it safely skips the operation.
if len(cols_to_cast) > 0:
    df = df.with_columns(
        pl.col(cols_to_cast).cast(pl.Int32)
    )
    print("Conversion effectuée :", cols_to_cast)
else:
    print("Aucune conversion effectuée.")

    # This block verifies the schema after the conversion check.
print(df.collect_schema())
print(df.shape)

Colonnes Int64 trouvées : []
Aucune colonne Int64 trouvée. Rien à convertir.
shape: (0, 4)
┌────────┬───────────┬───────────┬───────────────────┐
│ column ┆ min_value ┆ max_value ┆ can_cast_to_int32 │
│ ---    ┆ ---       ┆ ---       ┆ ---               │
│ str    ┆ i64       ┆ i64       ┆ bool              │
╞════════╪═══════════╪═══════════╪═══════════════════╡
└────────┴───────────┴───────────┴───────────────────┘
Colonnes à convertir : []
Aucune conversion effectuée.
Schema({'cmplnt_num': String, 'cmplnt_fr_dt': String, 'cmplnt_fr_tm': String, 'cmplnt_to_dt': String, 'cmplnt_to_tm': String, 'addr_pct_cd': Int32, 'rpt_dt': String, 'ky_cd': Int32, 'ofns_desc': String, 'pd_cd': Int32, 'pd_desc': String, 'crm_atpt_cptd_cd': String, 'law_cat_cd': String, 'boro_nm': String, 'loc_of_occur_desc': String, 'prem_typ_desc': String, 'juris_desc': String, 'jurisdiction_code': Int32, 'parks_nm': String, 'hadevelopt': String, 'housing_psa': String, 'x_coord_cd': Int32, 'y_coord_cd': Int32, 'susp_age_group': String, 'susp_race': String, 'susp_sex': String, 'transit_district': String, 'latitude': Float64, 'longitude': Float64, 'lat_lon': String, 'patrol_boro': String, 'station_name': String, 'vic_age_group': String, 'vic_race': String, 'vic_sex': String})
(8353049, 35)

#### 6 Sauvez toutes vos modifications faites en un format parquet et vérifiez le résultat

<br>

In [94]:
df.write_csv("data/new_NYPD_data.csv")
# This block saves the cleaned DataFrame into a Parquet file.
df.write_parquet("data/new_NYPD_data.parquet")

In [123]:
df_lazy= df.lazy()
df_lazy.sink_csv("data/new_NYPD_data_cleaned.csv")
df_lazy.sink_parquet("data/new_NYPD_data_cleaned.parquet")

In [124]:
# This block reads the saved Parquet file and checks the result.
df_check = pl.read_parquet("data/new_NYPD_data_cleaned.parquet")

print(df_check.shape)
print(df_check.schema)

df_check.head(5)

(8353049, 35)
Schema({'cmplnt_num': String, 'cmplnt_fr_dt': String, 'cmplnt_fr_tm': String, 'cmplnt_to_dt': String, 'cmplnt_to_tm': String, 'addr_pct_cd': Int32, 'rpt_dt': String, 'ky_cd': Int32, 'ofns_desc': String, 'pd_cd': Int32, 'pd_desc': String, 'crm_atpt_cptd_cd': String, 'law_cat_cd': String, 'boro_nm': String, 'loc_of_occur_desc': String, 'prem_typ_desc': String, 'juris_desc': String, 'jurisdiction_code': Int32, 'parks_nm': String, 'hadevelopt': String, 'housing_psa': String, 'x_coord_cd': Int32, 'y_coord_cd': Int32, 'susp_age_group': String, 'susp_race': String, 'susp_sex': String, 'transit_district': String, 'latitude': Float64, 'longitude': Float64, 'lat_lon': String, 'patrol_boro': String, 'station_name': String, 'vic_age_group': String, 'vic_race': String, 'vic_sex': String})

shape: (5, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_fr ┆ cmplnt_to ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _tm       ┆ _dt       ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ (null)    ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ (null)    ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 10/19/2005 ┆ 20:30:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ F       │
│ 23893731   ┆ 12/04/2005 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ (null)    ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [ ]:
# This block reads the saved CSV file back and checks the result.
df_check_csv = pl.read_csv("data/new_NYPD_data.csv")

print(df_check_csv.shape)
print(df_check_csv.schema)

df_check_csv.head(5)

df_check_parquet = pl.read_parquet("data/new_NYPD_data.parquet")

print(df_check_parquet.shape)
print(df_check_parquet.schema)

df_check_parquet.head(5)

(8353049, 35)
Schema({'cmplnt_num': String, 'cmplnt_fr_dt': String, 'cmplnt_fr_tm': String, 'cmplnt_to_dt': String, 'cmplnt_to_tm': String, 'addr_pct_cd': Int64, 'rpt_dt': String, 'ky_cd': Int64, 'ofns_desc': String, 'pd_cd': Int64, 'pd_desc': String, 'crm_atpt_cptd_cd': String, 'law_cat_cd': String, 'boro_nm': String, 'loc_of_occur_desc': String, 'prem_typ_desc': String, 'juris_desc': String, 'jurisdiction_code': Int64, 'parks_nm': String, 'hadevelopt': String, 'housing_psa': String, 'x_coord_cd': Int64, 'y_coord_cd': Int64, 'susp_age_group': String, 'susp_race': String, 'susp_sex': String, 'transit_district': String, 'latitude': Float64, 'longitude': Float64, 'lat_lon': String, 'patrol_boro': String, 'station_name': String, 'vic_age_group': String, 'vic_race': String, 'vic_sex': String})
(8353049, 35)
Schema({'cmplnt_num': String, 'cmplnt_fr_dt': String, 'cmplnt_fr_tm': String, 'cmplnt_to_dt': String, 'cmplnt_to_tm': String, 'addr_pct_cd': Int32, 'rpt_dt': String, 'ky_cd': Int32, 'ofns_desc': String, 'pd_cd': Int32, 'pd_desc': String, 'crm_atpt_cptd_cd': String, 'law_cat_cd': String, 'boro_nm': String, 'loc_of_occur_desc': String, 'prem_typ_desc': String, 'juris_desc': String, 'jurisdiction_code': Int32, 'parks_nm': String, 'hadevelopt': String, 'housing_psa': String, 'x_coord_cd': Int32, 'y_coord_cd': Int32, 'susp_age_group': String, 'susp_race': String, 'susp_sex': String, 'transit_district': String, 'latitude': Float64, 'longitude': Float64, 'lat_lon': String, 'patrol_boro': String, 'station_name': String, 'vic_age_group': String, 'vic_race': String, 'vic_sex': String})

shape: (5, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_fr ┆ cmplnt_to ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _tm       ┆ _dt       ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ (null)    ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ (null)    ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 10/19/2005 ┆ 20:30:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ F       │
│ 23893731   ┆ 12/04/2005 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ (null)    ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 7 Affichez les 5 premières lignes des colonnes 'ofns_desc' et 'pd_desc'

<br>

In [107]:
df_check_parquet=pl.read_parquet("data/new_NYPD_data.parquet")

print(df_check_parquet.head(5))

print(
    df_check_parquet
.select(
    pl.col('ofns_desc'),
    pl.col('pd_desc')
    ).limit(5)
)

shape: (5, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_fr ┆ cmplnt_to ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _tm       ┆ _dt       ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ (null)    ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ (null)    ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 10/19/2005 ┆ 20:30:00  ┆ null      ┆ … ┆ (null)    ┆ 25-44     ┆ BLACK    ┆ F       │
│ 23893731   ┆ 12/04/2005 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ (null)    ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘
shape: (5, 2)
┌────────────────────────────────┬─────────────────────────────────┐
│ ofns_desc                      ┆ pd_desc                         │
│ ---                            ┆ ---                             │
│ str                            ┆ str                             │
╞════════════════════════════════╪═════════════════════════════════╡
│ RAPE                           ┆ RAPE 1                          │
│ GRAND LARCENY OF MOTOR VEHICLE ┆ LARCENY,GRAND OF AUTO           │
│ UNAUTHORIZED USE OF A VEHICLE  ┆ UNAUTHORIZED USE VEHICLE 3      │
│ MISCELLANEOUS PENAL LAW        ┆ UNAUTHORIZED USE VEHICLE 2      │
│ GRAND LARCENY                  ┆ LARCENY,GRAND BY THEFT OF CRED… │
└────────────────────────────────┴─────────────────────────────────┘

In [134]:
data.select(pl.col('ofns_desc', 'pd_desc')).head(5)
#df_lazy.select(pl.col('ofns_desc', 'pd_desc')).show_graph()

shape: (5, 2)
┌────────────────────────────────┬─────────────────────────────────┐
│ ofns_desc                      ┆ pd_desc                         │
│ ---                            ┆ ---                             │
│ str                            ┆ str                             │
╞════════════════════════════════╪═════════════════════════════════╡
│ RAPE                           ┆ RAPE 1                          │
│ GRAND LARCENY OF MOTOR VEHICLE ┆ LARCENY,GRAND OF AUTO           │
│ UNAUTHORIZED USE OF A VEHICLE  ┆ UNAUTHORIZED USE VEHICLE 3      │
│ MISCELLANEOUS PENAL LAW        ┆ UNAUTHORIZED USE VEHICLE 2      │
│ GRAND LARCENY                  ┆ LARCENY,GRAND BY THEFT OF CRED… │
└────────────────────────────────┴─────────────────────────────────┘

#### 8 Afficher le nombre d'incidents recensés pour le quartier de Manhattan

<br>

In [108]:

# This block does the same operation in a more compact form.
df_check_parquet.filter(
    pl.col("boro_nm") == "MANHATTAN"
).select(
    ["ofns_desc", "pd_desc"]
).limit(5)

shape: (5, 2)
┌──────────────────────────────┬────────────────────────────┐
│ ofns_desc                    ┆ pd_desc                    │
│ ---                          ┆ ---                        │
│ str                          ┆ str                        │
╞══════════════════════════════╪════════════════════════════╡
│ RAPE                         ┆ RAPE 1                     │
│ ASSAULT 3 & RELATED OFFENSES ┆ ASSAULT 3                  │
│ HARRASSMENT 2                ┆ HARASSMENT,SUBD 3,4,5      │
│ HARRASSMENT 2                ┆ HARASSMENT,SUBD 1,CIVILIAN │
│ ASSAULT 3 & RELATED OFFENSES ┆ ASSAULT 3                  │
└──────────────────────────────┴────────────────────────────┘

In [109]:
# This block filters the DataFrame for Manhattan and counts the number of matching incidents.
manhattan_count = (
    df_check_parquet
    .filter(pl.col("boro_nm") == "MANHATTAN")
    .select(
        pl.len().alias("nombre_incidents_manhattan")
    )
)

manhattan_count

shape: (1, 1)
┌────────────────────────────┐
│ nombre_incidents_manhattan │
│ ---                        │
│ u32                        │
╞════════════════════════════╡
│ 2016172                    │
└────────────────────────────┘

In [111]:
# This block directly counts Manhattan incidents.
df_check_parquet.filter(pl.col("boro_nm") == "MANHATTAN").select(pl.len())

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 2016172 │
└─────────┘

#### 9 Est-ce que des  patrouilles du quartier de Brooklyn ou du Queens peuvent intervenir à Manhattan ?

<br>

In [112]:
# This block displays the distinct patrol borough values.
df.select(
    pl.col("patrol_boro").unique().sort()
)

shape: (9, 1)
┌───────────────────────────┐
│ patrol_boro               │
│ ---                       │
│ str                       │
╞═══════════════════════════╡
│ (null)                    │
│ PATROL BORO BKLYN NORTH   │
│ PATROL BORO BKLYN SOUTH   │
│ PATROL BORO BRONX         │
│ PATROL BORO MAN NORTH     │
│ PATROL BORO MAN SOUTH     │
│ PATROL BORO QUEENS NORTH  │
│ PATROL BORO QUEENS SOUTH  │
│ PATROL BORO STATEN ISLAND │
└───────────────────────────┘

In [113]:
# This block counts incidents in Manhattan by patrol borough.
(
    df
    .filter(pl.col("boro_nm") == "MANHATTAN")
    .group_by("patrol_boro")
    .agg(
        pl.len().alias("nombre_incidents")
    )
    .sort("nombre_incidents", descending=True)
)

shape: (9, 2)
┌───────────────────────────┬──────────────────┐
│ patrol_boro               ┆ nombre_incidents │
│ ---                       ┆ ---              │
│ str                       ┆ u32              │
╞═══════════════════════════╪══════════════════╡
│ PATROL BORO MAN SOUTH     ┆ 1016418          │
│ PATROL BORO MAN NORTH     ┆ 997075           │
│ PATROL BORO QUEENS NORTH  ┆ 2385             │
│ PATROL BORO QUEENS SOUTH  ┆ 81               │
│ PATROL BORO BRONX         ┆ 75               │
│ (null)                    ┆ 71               │
│ PATROL BORO BKLYN NORTH   ┆ 40               │
│ PATROL BORO BKLYN SOUTH   ┆ 17               │
│ PATROL BORO STATEN ISLAND ┆ 10               │
└───────────────────────────┴──────────────────┘

In [133]:
# This block filters Manhattan incidents where the patrol borough seems to be Brooklyn or Queens.
(
    df
    .filter(
        (pl.col("boro_nm") == "MANHATTAN")
        &
        (
            pl.col("patrol_boro").str.contains("BKLYN|BROOKLYN|QUEENS")
        )
    )
    .select(
        "boro_nm",
        "patrol_boro",
        "ofns_desc",
        "pd_desc"
    )
    .head(10)
)

shape: (10, 4)
┌───────────┬──────────────────────────┬─────────────────────────────┬─────────────────────────────┐
│ boro_nm   ┆ patrol_boro              ┆ ofns_desc                   ┆ pd_desc                     │
│ ---       ┆ ---                      ┆ ---                         ┆ ---                         │
│ str       ┆ str                      ┆ str                         ┆ str                         │
╞═══════════╪══════════════════════════╪═════════════════════════════╪═════════════════════════════╡
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ PETIT LARCENY               ┆ LARCENY,PETIT OF VEHICLE    │
│           ┆                          ┆                             ┆ ACCES                       │
│ MANHATTAN ┆ PATROL BORO QUEENS SOUTH ┆ THEFT-FRAUD                 ┆ FRAUD,UNCLASSIFIED-FELONY   │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ SEX CRIMES                  ┆ AGGRAVATED SEXUAL ASBUSE    │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ SEX CRIMES                  ┆ SEXUAL MISCONDUCT,DEVIATE   │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ SEX CRIMES                  ┆ AGGRAVATED SEXUAL ASBUSE    │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ HARRASSMENT 2               ┆ HARASSMENT,SUBD 1,CIVILIAN  │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ GRAND LARCENY               ┆ LARCENY,GRAND BY EXTORTION  │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ OTHER OFFENSES RELATED TO   ┆ THEFT OF SERVICES,          │
│           ┆                          ┆ THEF                        ┆ UNCLASSIFIE                 │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ PETIT LARCENY               ┆ LARCENY,PETIT OF LICENSE    │
│           ┆                          ┆                             ┆ PLATE                       │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH ┆ GRAND LARCENY               ┆ LARCENY,GRAND BY ACQUIRING  │
│           ┆                          ┆                             ┆ LOS                         │
└───────────┴──────────────────────────┴─────────────────────────────┴─────────────────────────────┘

In [129]:
# This block counts Manhattan incidents handled by Brooklyn or Queens patrol boroughs.
(
    df
    .filter(
        (pl.col("boro_nm") == "MANHATTAN")
        &
        (
            pl.col("patrol_boro").str.contains("BKLYN|BROOKLYN|QUEENS")
        )
    )
    .select(
        pl.len().alias("nombre_interventions_brooklyn_queens_a_manhattan").unique()
    )
)

shape: (1, 1)
┌─────────────────────────────────┐
│ nombre_interventions_brooklyn_… │
│ ---                             │
│ u32                             │
╞═════════════════════════════════╡
│ 2523                            │
└─────────────────────────────────┘

#### 10 Renseignez-vous sur la notion de precinct (colonne addr_pct_cd). Combien en comptabilisez-vous ?

<br>

In [117]:
# This block counts the number of distinct non-null precincts in addr_pct_cd.
nb_precincts = (
    data
    .filter(pl.col("addr_pct_cd").is_not_null())
    .select(
        pl.col("addr_pct_cd").n_unique().alias("nb_precincts")
    )
    
)

nb_precincts

shape: (1, 1)
┌──────────────┐
│ nb_precincts │
│ ---          │
│ u32          │
╞══════════════╡
│ 77           │
└──────────────┘

In [119]:
# This block displays the distinct precinct codes, sorted increasingly.
precincts = (
    data
    .filter(pl.col("addr_pct_cd").is_not_null())
    .select("addr_pct_cd")
    .unique()
    .sort("addr_pct_cd")
    
)

precincts

shape: (77, 1)
┌─────────────┐
│ addr_pct_cd │
│ ---         │
│ i32         │
╞═════════════╡
│ 1           │
│ 5           │
│ 6           │
│ 7           │
│ 9           │
│ …           │
│ 115         │
│ 120         │
│ 121         │
│ 122         │
│ 123         │
└─────────────┘

In [120]:
# This block counts the number of distinct non-null precincts in an eager DataFrame.
nb_precincts = (
    df
    .filter(pl.col("addr_pct_cd").is_not_null())
    .select(
        pl.col("addr_pct_cd").n_unique().alias("nb_precincts")
    )
)

nb_precincts

shape: (1, 1)
┌──────────────┐
│ nb_precincts │
│ ---          │
│ u32          │
╞══════════════╡
│ 77           │
└──────────────┘

#### 11 A quand remonte le dernier incident rapportant un avortement ?

<br>

#### 12  En moyenne, quel est le temps écoulé entre le début d'un rapport et de sa fin ?

<br>

#### 13 Est-ce que ce temps moyen est similaire entre les différents quartiers ? Triez par ordre décroissant et afficher également le nombre d'offenses recensées.

<br>

#### 14 Affichez par année et ce depuis 2010 la somme cumulée du nombre d'offenses de catégorie *Felony*

**BONUS**: Pouvez-vous constater une accélération ?

<br>

#### 15 Affichez toutes les valeurs uniques présentes dans la colonne 'ofns_desc' ainsi que leur nombre d'occurences

**BONUS:** Trouvez une solution afin d'afficher le résultat dans deux colonnes distinctes et triez par ordre décroissant sur le nombre d'occurences

<br>

#### 16 Quel est le top 5 des offenses les plus recensées en 2020

<br>

#### 17 Parmi ce top 5, quels sont les tranches d'âge les plus touchées en 2020 ?

<br>

#### 18 Afficher l'évolution(en valeur absolue et en %), d'année en année, du nombre d'offenses faites aux femmes depuis 2010

<br>

#### 19 Affichez le nombre d'enregistrements par jour de la semaine(*e.g.* lundi, mardi, *etc.*) et ce pour Manhattan

<br>

#### 20 Ajoutez une colonne aux données qui doit permettre d'identifier des moments dans les journées en fonction de l'heure

*e.g.*:
- entre 22h00 et 04h59 => NIGHT
- entre 05H00 et 18h59 => DAY
- entre 19h00 et 21h59 => EVENING

Ensuite afficher le nombre d'enregistements par période et par type d'infraction(*i.e.* law_cat_cd)

<br>

#### 21 Afin de pouvoir trier correctement le résultat de l'exercice précédent, ajoutez une colonne reprenenant le niveau de gravité:

- 1: 'FELONY'
- 2: 'MISDEMEANOR'
- 3: 'VIOLATION'

#### 22 Reprenez l'exercice précédent mais en ne gardant que les cinq dernières années disponnibles et en excluant les infractions les plus minimes

<br>

#### 23 Proposez un crosstab avec le nombre d'enregistrements par type d'infractions et moment de la journée

Plusieurs remarques:
- nous voudrions également avoir non pas les valeurs absolues mais les ratios. Ces ratios peuvent être calculer de trois façons:
    - en divisant chaque cellule par la somme de sa colonne
    - en divisant chaque cellule par la somme de sa ligne
    - en divisant chaque cellule par le total de la matrice
- l'exercice est plus facile à réaliser si vous passez par Pandas qui propose une solution avec crosstab. Nous voudrions que vous proposiez également une solution sans passer par Pandas.

<br>

#### 24 Identifiez les offenses qui ont connu, en moyenne, la plus grande progression sur les 10 dernières années disponnibles

**Compléments d'informations**: nous voulons pour chaque offense et pour chaque année avoir son nombre d'occurences et afficher sa progression par rapport à n-1 et ensuite faire une moyenne sur ces progressions.

<br>

#### 25 Filtrez afin de ne garder que les offenses avec au minimum 1000 enregistrements

##### 25.1 Affichez également le top et bottom 10

<br>

#### 26 A l'aide d'une fenêtre, identifiez les moments dans la journée et dans l'année qui répertorient le plus de plaintes

<br>

#### 26.1 Pouvez-vous constater une différence entre les différentes gravités de crimes ? Certains crimes ont-ils tendance a plus être commis à telle ou telle heure de la journée ?

<br>

#### 27 Et quelle est la période dans l'année la plus propice ?

<br>