# Exercices Polars

La série suivante d'exercices doit vous permettre de maîtriser les rudiments de Polars. Elle présupose que vous ayez déjà les bases avec Pandas et SQL.

Toutes les fonctions et méthodes nécessaires à cette série n'ont bien évidemment été pas abordées durant la session théorique et ces exercices vous forceront à trouver des pistes de solution dans la [documentation](https://www.pola.rs/) officielle.

Soyez curieux et n'hésitez pas à aller plus loin que les énoncés et à analyser plus en profondeur le dataset proposé.

**Conseil:** Si des exercices vous résistent, fragmentez votre problème en petits morceaux. N'hésitez pas à lister les différentes étapes nécessaire à l'élaboration des exercices avant de vous lancer dans le code.

<br>

#### 1 Procurez-vous le fichier [ici](https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i) et affichez les 5 premières lignes

**Conseil:** avant d'aller plus loin, prenez le temps de lire les informations présentes afin de bien comprendre les données avec lesquelles vous travaillerez.

<br>

In [47]:
import polars as pl

In [50]:
file_path = "data/data_exo/data/NYPD_complaints_all.csv"
data = pl.scan_csv(
    file_path, infer_schema_length=100000
    , null_values=["", "NA", "NaN", "null", "NULL", '(null)']
    )

data.head(5).collect()

shape: (5, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 10/19/2005 ┆ 20:30:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│ 23893731   ┆ 12/04/2005 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 2 Affichez le nombre de lignes, de colonnes, le schéma ainsi que le poids total du fichier en mémoire

<br>

In [51]:
data.select(pl.len()).collect()
len(data.collect_schema())
data.collect().estimated_size(unit='mb')

2512.9604539871216

#### 3 Affichez le nombre et la proportion de valeurs manquantes par colonne et pour le dataset au complet

<br>

In [52]:
# %%timeit
data.null_count().collect()

shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 48        ┆ 1778361   ┆ … ┆ 8169741   ┆ 1623390   ┆ 561      ┆ 308     │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [53]:
# %%timeit
data.select(pl.all().is_null()).collect().sum()

shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 48        ┆ 1778361   ┆ … ┆ 8169741   ┆ 1623390   ┆ 561      ┆ 308     │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [54]:
n_rows = data.select(pl.len()).collect()
display(n_rows)
n_rows.get_column('len')[0]

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 8353049 │
└─────────┘

8353049

In [55]:
n_rows = data.select(pl.len()).collect().get_column('len')[0]
nulls_count = data.null_count().collect()

display(nulls_count)

nulls_count\
    .transpose(
        include_header=True, header_name='column_name'
        , column_names=['null_count']
    )\
    .with_columns(
        null_ratio = pl.col('null_count')/n_rows
    ).sort('null_count', descending=True)

shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 48        ┆ 1778361   ┆ … ┆ 8169741   ┆ 1623390   ┆ 561      ┆ 308     │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

shape: (35, 3)
┌───────────────────┬────────────┬────────────┐
│ column_name       ┆ null_count ┆ null_ratio │
│ ---               ┆ ---        ┆ ---        │
│ str               ┆ u32        ┆ f64        │
╞═══════════════════╪════════════╪════════════╡
│ HADEVELOPT        ┆ 8323205    ┆ 0.996427   │
│ PARKS_NM          ┆ 8318817    ┆ 0.995902   │
│ TRANSIT_DISTRICT  ┆ 8169741    ┆ 0.978055   │
│ STATION_NAME      ┆ 8169741    ┆ 0.978055   │
│ HOUSING_PSA       ┆ 7719467    ┆ 0.92415    │
│ …                 ┆ …          ┆ …          │
│ RPT_DT            ┆ 0          ┆ 0.0        │
│ KY_CD             ┆ 0          ┆ 0.0        │
│ LAW_CAT_CD        ┆ 0          ┆ 0.0        │
│ JURIS_DESC        ┆ 0          ┆ 0.0        │
│ JURISDICTION_CODE ┆ 0          ┆ 0.0        │
└───────────────────┴────────────┴────────────┘

#### 4 Pour vous simplifier la vie avec le reste des exercices, mettez en minuscule le nom des colonnes

#### 4.1 Pensez également à convertir les colonnes qui devraient être en DateTime et éventuellement à regrouper les parties Date et Time

#### 4.2 Retirez les colonnes 'cmplnt_fr_tm' et 'cmplnt_to_tm' puisque vous avez tout regroupé dans une seule et même colonne

<br>

In [56]:
data.head(5).collect()

shape: (5, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 10/19/2005 ┆ 20:30:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│ 23893731   ┆ 12/04/2005 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [57]:
# CMPLNT_FR_DT	CMPLNT_FR_TM	CMPLNT_TO_DT	CMPLNT_TO_TM
# .str.to_datetime(format='%m/%d/%Y')
data = data.select(pl.all().name.to_lowercase())\
    .with_columns(
        cmplnt_fr_dt = pl.concat_str(
            [pl.col('cmplnt_fr_dt'), pl.col('cmplnt_fr_tm')]
            , separator=' '
        ).str.to_datetime(format='%m/%d/%Y %H:%M:%S')
        , cmplnt_to_dt = pl.concat_str(
            [pl.col('cmplnt_to_dt'), pl.col('cmplnt_to_tm')]
            , separator=' '
        ).str.to_datetime(format='%m/%d/%Y %H:%M:%S')
    ).select(pl.exclude('cmplnt_fr_tm', 'cmplnt_to_tm'))

data.head(5).collect()

shape: (5, 33)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ datetime[μ ┆ datetime[ ┆ i64       ┆   ┆ str       ┆ str       ┆          ┆         │
│            ┆ s]         ┆ μs]       ┆           ┆   ┆           ┆           ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 2002-01-01 ┆ 2006-02-2 ┆ null      ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆ 11:00:00   ┆ 5         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 11:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 2005-04-22 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│            ┆ 02:00:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10832306   ┆ 2005-07-11 ┆ 2006-03-2 ┆ null      ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆ 20:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 12:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 2005-10-19 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│            ┆ 20:30:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 23893731   ┆ 2005-12-04 ┆ 2006-08-0 ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆ 09:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 17:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 5 Vérifiez si les colonnes en Int64 peuvent être converties en Int32 afin de gagner en espace mémoire

<br>

In [58]:
import numpy as np
np.array([1, 256, 257, 1000]).astype(np.uint8)

array([  1,   0,   1, 232], dtype=uint8)

In [59]:
1000%256

232

In [60]:
overflow = pl.DataFrame(
    {
        'values': [1, 256, 257, 1000]
    }
)
display(overflow)
overflow.cast({'values': pl.UInt8}, strict=False)

shape: (4, 1)
┌────────┐
│ values │
│ ---    │
│ i64    │
╞════════╡
│ 1      │
│ 256    │
│ 257    │
│ 1000   │
└────────┘

shape: (4, 1)
┌────────┐
│ values │
│ ---    │
│ u8     │
╞════════╡
│ 1      │
│ null   │
│ null   │
│ null   │
└────────┘

In [61]:
data = data.cast({pl.Int64: pl.Int32})
data.collect_schema()

Schema([('cmplnt_num', String),
        ('cmplnt_fr_dt', Datetime(time_unit='us', time_zone=None)),
        ('cmplnt_to_dt', Datetime(time_unit='us', time_zone=None)),
        ('addr_pct_cd', Int32),
        ('rpt_dt', String),
        ('ky_cd', Int32),
        ('ofns_desc', String),
        ('pd_cd', Int32),
        ('pd_desc', String),
        ('crm_atpt_cptd_cd', String),
        ('law_cat_cd', String),
        ('boro_nm', String),
        ('loc_of_occur_desc', String),
        ('prem_typ_desc', String),
        ('juris_desc', String),
        ('jurisdiction_code', Int32),
        ('parks_nm', String),
        ('hadevelopt', String),
        ('housing_psa', Int32),
        ('x_coord_cd', Int32),
        ('y_coord_cd', Int32),
        ('susp_age_group', String),
        ('susp_race', String),
        ('susp_sex', String),
        ('transit_district', Int32),
        ('latitude', Float64),
        ('longitude', Float64),
        ('lat_lon', String),
        ('patrol_boro', String),
        ('station_name', String),
        ('vic_age_group', String),
        ('vic_race', String),
        ('vic_sex', String)])

In [62]:
data.collect().estimated_size(unit='mb')

2130.2271013259888

#### 6 Sauvez toutes vos modifications faites en un format parquet et vérifiez le résultat

<br>

In [63]:
data.sink_parquet('data/data_cleaned.parquet')

In [64]:
data = pl.scan_parquet('data/data_cleaned.parquet')
data.head(5).collect()

shape: (5, 33)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ datetime[μ ┆ datetime[ ┆ i32       ┆   ┆ str       ┆ str       ┆          ┆         │
│            ┆ s]         ┆ μs]       ┆           ┆   ┆           ┆           ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 2002-01-01 ┆ 2006-02-2 ┆ null      ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆ 11:00:00   ┆ 5         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 11:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 2005-04-22 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│            ┆ 02:00:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10832306   ┆ 2005-07-11 ┆ 2006-03-2 ┆ null      ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆ 20:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 12:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 2005-10-19 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│            ┆ 20:30:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 23893731   ┆ 2005-12-04 ┆ 2006-08-0 ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆ 09:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 17:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 7 Affichez les 5 premières lignes des colonnes 'ofns_desc' et 'pd_desc'

<br>

In [65]:
data.select(pl.col('ofns_desc', 'pd_desc')).head(5).collect()

shape: (5, 2)
┌────────────────────────────────┬─────────────────────────────────┐
│ ofns_desc                      ┆ pd_desc                         │
│ ---                            ┆ ---                             │
│ str                            ┆ str                             │
╞════════════════════════════════╪═════════════════════════════════╡
│ RAPE                           ┆ RAPE 1                          │
│ GRAND LARCENY OF MOTOR VEHICLE ┆ LARCENY,GRAND OF AUTO           │
│ UNAUTHORIZED USE OF A VEHICLE  ┆ UNAUTHORIZED USE VEHICLE 3      │
│ MISCELLANEOUS PENAL LAW        ┆ UNAUTHORIZED USE VEHICLE 2      │
│ GRAND LARCENY                  ┆ LARCENY,GRAND BY THEFT OF CRED… │
└────────────────────────────────┴─────────────────────────────────┘

#### 8 Afficher le nombre d'incidents recensés pour le quartier de Manhattan

<br>

In [66]:
# %%timeit
data.select(pl.col('boro_nm'))\
    .filter(pl.col('boro_nm') == 'MANHATTAN')\
    .select(pl.len())\
    .collect()

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 2016172 │
└─────────┘

In [67]:
# %%timeit
data.select(pl.col('boro_nm'))\
    .filter(pl.col('boro_nm') == 'MANHATTAN')\
    .count()\
    .collect()

shape: (1, 1)
┌─────────┐
│ boro_nm │
│ ---     │
│ u32     │
╞═════════╡
│ 2016172 │
└─────────┘

#### 9 Est-ce que des  patrouilles du quartier de Brooklyn ou du Queens peuvent intervenir à Manhattan ?

<br>

In [68]:
# boro_nm = 'MANHATTAN' & patrol_bora == 
data.filter(
    (pl.col('boro_nm') == 'MANHATTAN')
    & (
        pl.col('patrol_boro').str.contains('BKLYN')
        | pl.col('patrol_boro').str.contains('QUEENS')
    )
).select(pl.col('boro_nm', 'patrol_boro')).unique().collect()

shape: (4, 2)
┌───────────┬──────────────────────────┐
│ boro_nm   ┆ patrol_boro              │
│ ---       ┆ ---                      │
│ str       ┆ str                      │
╞═══════════╪══════════════════════════╡
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH │
│ MANHATTAN ┆ PATROL BORO QUEENS SOUTH │
│ MANHATTAN ┆ PATROL BORO BKLYN SOUTH  │
│ MANHATTAN ┆ PATROL BORO BKLYN NORTH  │
└───────────┴──────────────────────────┘

#### 10 Renseignez-vous sur la notion de precinct (colonne addr_pct_cd). Combien en comptabilisez-vous ?

<br>

#### 11 A quand remonte le dernier incident rapportant un avortement ?

<br>

In [69]:
# %%timeit
data.filter(
    pl.col('ofns_desc') == 'ABORTION'
).select(pl.col('cmplnt_fr_dt')).max().collect()

shape: (1, 1)
┌─────────────────────┐
│ cmplnt_fr_dt        │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2018-04-20 23:00:00 │
└─────────────────────┘

In [70]:
# %%timeit
data.filter(
    pl.col('ofns_desc') == 'ABORTION'
).sort('cmplnt_fr_dt', descending=True).select(pl.col('cmplnt_fr_dt')).head(1).collect()

shape: (1, 1)
┌─────────────────────┐
│ cmplnt_fr_dt        │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2018-04-20 23:00:00 │
└─────────────────────┘

#### 12  En moyenne, quel est le temps écoulé entre le début d'un rapport et de sa fin ?

<br>

In [71]:
data\
    .filter(
        pl.col('cmplnt_fr_dt').is_not_null()
        & pl.col('cmplnt_to_dt').is_not_null()
    )\
    .select(
        # pl.col('cmplnt_fr_dt', 'cmplnt_to_dt')
        (pl.col('cmplnt_to_dt')-pl.col('cmplnt_fr_dt')).alias('duration')
    ).median().collect()

shape: (1, 1)
┌──────────────┐
│ duration     │
│ ---          │
│ duration[μs] │
╞══════════════╡
│ 18m          │
└──────────────┘

#### 13 Est-ce que ce temps moyen est similaire entre les différents quartiers ? Triez par ordre décroissant et afficher également le nombre d'offenses recensées.

<br>

In [72]:
data\
    .filter(
        pl.col('cmplnt_fr_dt').is_not_null()
        & pl.col('cmplnt_to_dt').is_not_null()
        # & pl.col('boro_nm').is_not_null()
    )\
    .select(
        # pl.col('cmplnt_fr_dt', 'cmplnt_to_dt')
        pl.col('boro_nm')
        , (pl.col('cmplnt_to_dt')-pl.col('cmplnt_fr_dt')).alias('duration')
    )\
    .group_by('boro_nm')\
    .agg(
        pl.col('duration').mean().alias('mean_duration')
        , pl.col('duration').median().alias('median_duration')
        , pl.len().alias('count')
    ).sort('mean_duration').collect()

shape: (6, 4)
┌───────────────┬──────────────────────────┬─────────────────┬─────────┐
│ boro_nm       ┆ mean_duration            ┆ median_duration ┆ count   │
│ ---           ┆ ---                      ┆ ---             ┆ ---     │
│ str           ┆ duration[μs]             ┆ duration[μs]    ┆ u32     │
╞═══════════════╪══════════════════════════╪═════════════════╪═════════╡
│ null          ┆ 6d 9h 45m 31s 831789µs   ┆ 24m             ┆ 4209    │
│ STATEN ISLAND ┆ 11d 22h 52m 52s 722319µs ┆ 25m             ┆ 292552  │
│ BRONX         ┆ 13d 7h 50m 14s 509833µs  ┆ 15m             ┆ 1253452 │
│ MANHATTAN     ┆ 13d 19h 27m 39s 904857µs ┆ 15m             ┆ 1584150 │
│ BROOKLYN      ┆ 15d 12h 46m 57s 153149µs ┆ 17m             ┆ 2002065 │
│ QUEENS        ┆ 18d 7h 40m 38s 394009µs  ┆ 20m             ┆ 1436485 │
└───────────────┴──────────────────────────┴─────────────────┴─────────┘

#### 14 Affichez par année et ce depuis 2010 la somme cumulée du nombre d'offenses de catégorie *Felony*

**BONUS**: Pouvez-vous constater une accélération ?

<br>

In [73]:
exo_14 = data\
    .filter(
        (pl.col('cmplnt_fr_dt').dt.year() >= 2010)
        & (pl.col('law_cat_cd') == 'FELONY')
    )\
    .group_by(pl.col('cmplnt_fr_dt').dt.year())\
    .agg(
        pl.len().alias('count')
    )\
    .sort('cmplnt_fr_dt')\
    .with_columns(cum_sum_count = pl.col('count').cum_sum())\

exo_14.collect()

shape: (13, 3)
┌──────────────┬────────┬───────────────┐
│ cmplnt_fr_dt ┆ count  ┆ cum_sum_count │
│ ---          ┆ ---    ┆ ---           │
│ i32          ┆ u32    ┆ u32           │
╞══════════════╪════════╪═══════════════╡
│ 2010         ┆ 147347 ┆ 147347        │
│ 2011         ┆ 148015 ┆ 295362        │
│ 2012         ┆ 153848 ┆ 449210        │
│ 2013         ┆ 154155 ┆ 603365        │
│ 2014         ┆ 151569 ┆ 754934        │
│ …            ┆ …      ┆ …             │
│ 2018         ┆ 140756 ┆ 1338502       │
│ 2019         ┆ 142041 ┆ 1480543       │
│ 2020         ┆ 135126 ┆ 1615669       │
│ 2021         ┆ 148913 ┆ 1764582       │
│ 2022         ┆ 172918 ┆ 1937500       │
└──────────────┴────────┴───────────────┘

In [74]:
exo_14.with_columns(
    pct_change_over_year = pl.col('count').pct_change(),
    pct_change_shift = pl.col('count').shift(1)
).collect()

shape: (13, 5)
┌──────────────┬────────┬───────────────┬──────────────────────┬──────────────────┐
│ cmplnt_fr_dt ┆ count  ┆ cum_sum_count ┆ pct_change_over_year ┆ pct_change_shift │
│ ---          ┆ ---    ┆ ---           ┆ ---                  ┆ ---              │
│ i32          ┆ u32    ┆ u32           ┆ f64                  ┆ u32              │
╞══════════════╪════════╪═══════════════╪══════════════════════╪══════════════════╡
│ 2010         ┆ 147347 ┆ 147347        ┆ null                 ┆ null             │
│ 2011         ┆ 148015 ┆ 295362        ┆ 0.004534             ┆ 147347           │
│ 2012         ┆ 153848 ┆ 449210        ┆ 0.039408             ┆ 148015           │
│ 2013         ┆ 154155 ┆ 603365        ┆ 0.001995             ┆ 153848           │
│ 2014         ┆ 151569 ┆ 754934        ┆ -0.016775            ┆ 154155           │
│ …            ┆ …      ┆ …             ┆ …                    ┆ …                │
│ 2018         ┆ 140756 ┆ 1338502       ┆ -0.011607            ┆ 142409           │
│ 2019         ┆ 142041 ┆ 1480543       ┆ 0.009129             ┆ 140756           │
│ 2020         ┆ 135126 ┆ 1615669       ┆ -0.048683            ┆ 142041           │
│ 2021         ┆ 148913 ┆ 1764582       ┆ 0.102031             ┆ 135126           │
│ 2022         ┆ 172918 ┆ 1937500       ┆ 0.161202             ┆ 148913           │
└──────────────┴────────┴───────────────┴──────────────────────┴──────────────────┘

In [75]:
exo_14.join(
    exo_14, how='inner'
    , left_on = 'cmplnt_fr_dt', right_on = pl.col('cmplnt_fr_dt')-1
).collect()

shape: (12, 6)
┌──────────────┬────────┬───────────────┬────────────────────┬─────────────┬─────────────────────┐
│ cmplnt_fr_dt ┆ count  ┆ cum_sum_count ┆ cmplnt_fr_dt_right ┆ count_right ┆ cum_sum_count_right │
│ ---          ┆ ---    ┆ ---           ┆ ---                ┆ ---         ┆ ---                 │
│ i32          ┆ u32    ┆ u32           ┆ i32                ┆ u32         ┆ u32                 │
╞══════════════╪════════╪═══════════════╪════════════════════╪═════════════╪═════════════════════╡
│ 2010         ┆ 147347 ┆ 147347        ┆ 2011               ┆ 148015      ┆ 295362              │
│ 2011         ┆ 148015 ┆ 295362        ┆ 2012               ┆ 153848      ┆ 449210              │
│ 2012         ┆ 153848 ┆ 449210        ┆ 2013               ┆ 154155      ┆ 603365              │
│ 2013         ┆ 154155 ┆ 603365        ┆ 2014               ┆ 151569      ┆ 754934              │
│ 2014         ┆ 151569 ┆ 754934        ┆ 2015               ┆ 150816      ┆ 905750              │
│ …            ┆ …      ┆ …             ┆ …                  ┆ …           ┆ …                   │
│ 2017         ┆ 142409 ┆ 1197746       ┆ 2018               ┆ 140756      ┆ 1338502             │
│ 2018         ┆ 140756 ┆ 1338502       ┆ 2019               ┆ 142041      ┆ 1480543             │
│ 2019         ┆ 142041 ┆ 1480543       ┆ 2020               ┆ 135126      ┆ 1615669             │
│ 2020         ┆ 135126 ┆ 1615669       ┆ 2021               ┆ 148913      ┆ 1764582             │
│ 2021         ┆ 148913 ┆ 1764582       ┆ 2022               ┆ 172918      ┆ 1937500             │
└──────────────┴────────┴───────────────┴────────────────────┴─────────────┴─────────────────────┘

## bonus bonus

In [76]:
data\
    .filter(
        (pl.col('cmplnt_fr_dt').dt.year() >= 2010)
    )\
    .group_by(pl.col('cmplnt_fr_dt').dt.year(), pl.col('boro_nm'))\
    .agg(
        pl.len().alias('count')
    )\
    .sort('cmplnt_fr_dt', 'boro_nm')\
    .with_columns(
        cum_sum_count = pl.col('count').cum_sum().over('boro_nm')
        , pct_change_over_year_boro = pl.col('count').pct_change().over('boro_nm')
        )\
    .collect().filter(pl.col('boro_nm') == 'BRONX')

shape: (13, 5)
┌──────────────┬─────────┬────────┬───────────────┬───────────────────────────┐
│ cmplnt_fr_dt ┆ boro_nm ┆ count  ┆ cum_sum_count ┆ pct_change_over_year_boro │
│ ---          ┆ ---     ┆ ---    ┆ ---           ┆ ---                       │
│ i32          ┆ str     ┆ u32    ┆ u32           ┆ f64                       │
╞══════════════╪═════════╪════════╪═══════════════╪═══════════════════════════╡
│ 2010         ┆ BRONX   ┆ 111741 ┆ 111741        ┆ null                      │
│ 2011         ┆ BRONX   ┆ 108782 ┆ 220523        ┆ -0.026481                 │
│ 2012         ┆ BRONX   ┆ 106969 ┆ 327492        ┆ -0.016666                 │
│ 2013         ┆ BRONX   ┆ 104206 ┆ 431698        ┆ -0.02583                  │
│ 2014         ┆ BRONX   ┆ 106343 ┆ 538041        ┆ 0.020507                  │
│ …            ┆ …       ┆ …      ┆ …             ┆ …                         │
│ 2018         ┆ BRONX   ┆ 100660 ┆ 952888        ┆ -0.024782                 │
│ 2019         ┆ BRONX   ┆ 100476 ┆ 1053364       ┆ -0.001828                 │
│ 2020         ┆ BRONX   ┆ 90787  ┆ 1144151       ┆ -0.096431                 │
│ 2021         ┆ BRONX   ┆ 94106  ┆ 1238257       ┆ 0.036558                  │
│ 2022         ┆ BRONX   ┆ 110031 ┆ 1348288       ┆ 0.169224                  │
└──────────────┴─────────┴────────┴───────────────┴───────────────────────────┘

#### 15 Affichez toutes les valeurs uniques présentes dans la colonne 'ofns_desc' ainsi que leur nombre d'occurences

**BONUS:** Trouvez une solution afin d'afficher le résultat dans deux colonnes distinctes et triez par ordre décroissant sur le nombre d'occurences

<br>

In [77]:
# context manager
with pl.Config() as cfg:
    cfg.set_tbl_rows(80)

    tmp = data.select(
        pl.col('ofns_desc').value_counts()
        ).unnest().sort('count', descending=True).collect()
    display(tmp)

shape: (73, 2)
┌─────────────────────────────────┬─────────┐
│ ofns_desc                       ┆ count   │
│ ---                             ┆ ---     │
│ str                             ┆ u32     │
╞═════════════════════════════════╪═════════╡
│ PETIT LARCENY                   ┆ 1446716 │
│ HARRASSMENT 2                   ┆ 1103353 │
│ ASSAULT 3 & RELATED OFFENSES    ┆ 876955  │
│ CRIMINAL MISCHIEF & RELATED OF  ┆ 834295  │
│ GRAND LARCENY                   ┆ 732709  │
│ DANGEROUS DRUGS                 ┆ 443469  │
│ OFF. AGNST PUB ORD SENSBLTY &   ┆ 418932  │
│ FELONY ASSAULT                  ┆ 335944  │
│ ROBBERY                         ┆ 297954  │
│ BURGLARY                        ┆ 283348  │
│ MISCELLANEOUS PENAL LAW         ┆ 216024  │
│ DANGEROUS WEAPONS               ┆ 173690  │
│ GRAND LARCENY OF MOTOR VEHICLE  ┆ 157994  │
│ OFFENSES AGAINST PUBLIC ADMINI  ┆ 149697  │
│ VEHICLE AND TRAFFIC LAWS        ┆ 113532  │
│ SEX CRIMES                      ┆ 103073  │
│ INTOXICATED & IMPAIRED DRIVING  ┆ 101824  │
│ CRIMINAL TRESPASS               ┆ 86284   │
│ THEFT-FRAUD                     ┆ 83476   │
│ FORGERY                         ┆ 82988   │
│ FRAUDS                          ┆ 48893   │
│ POSSESSION OF STOLEN PROPERTY   ┆ 40045   │
│ OFFENSES INVOLVING FRAUD        ┆ 28761   │
│ RAPE                            ┆ 24823   │
│ UNAUTHORIZED USE OF A VEHICLE   ┆ 24739   │
│ OFFENSES AGAINST THE PERSON     ┆ 20374   │
│ ARSON                           ┆ 18952   │
│ null                            ┆ 18868   │
│ ADMINISTRATIVE CODE             ┆ 18223   │
│ OTHER OFFENSES RELATED TO THEF  ┆ 17591   │
│ NYS LAWS-UNCLASSIFIED FELONY    ┆ 8002    │
│ OTHER STATE LAWS (NON PENAL LA  ┆ 7621    │
│ THEFT OF SERVICES               ┆ 4834    │
│ BURGLAR'S TOOLS                 ┆ 4414    │
│ FRAUDULENT ACCOSTING            ┆ 3555    │
│ GAMBLING                        ┆ 3348    │
│ KIDNAPPING & RELATED OFFENSES   ┆ 3135    │
│ MURDER & NON-NEGL. MANSLAUGHTE… ┆ 1780    │
│ OFFENSES RELATED TO CHILDREN    ┆ 1715    │
│ PETIT LARCENY OF MOTOR VEHICLE  ┆ 1637    │
│ PROSTITUTION & RELATED OFFENSE… ┆ 1487    │
│ ALCOHOLIC BEVERAGE CONTROL LAW  ┆ 1386    │
│ OFFENSES AGAINST PUBLIC SAFETY  ┆ 1227    │
│ DISORDERLY CONDUCT              ┆ 1071    │
│ AGRICULTURE & MRKTS LAW-UNCLAS… ┆ 956     │
│ CHILD ABANDONMENT/NON SUPPORT   ┆ 515     │
│ JOSTLING                        ┆ 463     │
│ OTHER STATE LAWS                ┆ 383     │
│ ENDAN WELFARE INCOMP            ┆ 322     │
│ LOITERING/GAMBLING (CARDS, DIC  ┆ 258     │
│ ESCAPE 3                        ┆ 223     │
│ HOMICIDE-NEGLIGENT,UNCLASSIFIE  ┆ 203     │
│ ANTICIPATORY OFFENSES           ┆ 148     │
│ HOMICIDE-NEGLIGENT-VEHICLE      ┆ 123     │
│ NEW YORK CITY HEALTH CODE       ┆ 101     │
│ UNLAWFUL POSS. WEAP. ON SCHOOL  ┆ 88      │
│ NYS LAWS-UNCLASSIFIED VIOLATIO… ┆ 76      │
│ CANNABIS RELATED OFFENSES       ┆ 75      │
│ INTOXICATED/IMPAIRED DRIVING    ┆ 69      │
│ KIDNAPPING                      ┆ 67      │
│ DISRUPTION OF A RELIGIOUS SERV  ┆ 59      │
│ FELONY SEX CRIMES               ┆ 40      │
│ LOITERING FOR DRUG PURPOSES     ┆ 23      │
│ LOITERING                       ┆ 23      │
│ ADMINISTRATIVE CODES            ┆ 19      │
│ OTHER TRAFFIC INFRACTION        ┆ 16      │
│ LOITERING/DEVIATE SEX           ┆ 16      │
│ OTHER STATE LAWS (NON PENAL LA… ┆ 15      │
│ FORTUNE TELLING                 ┆ 12      │
│ ABORTION                        ┆ 7       │
│ OFFENSES AGAINST MARRIAGE UNCL  ┆ 5       │
│ UNDER THE INFLUENCE OF DRUGS    ┆ 3       │
│ KIDNAPPING AND RELATED OFFENSE… ┆ 3       │
└─────────────────────────────────┴─────────┘

#### 16 Quel est le top 5 des offenses les plus recensées en 2020

<br>

In [78]:
data.filter(
    pl.col('cmplnt_fr_dt').dt.year() == 2020
).select(
    pl.col('ofns_desc').value_counts()
).unnest().sort('count', descending=True).head(5).collect()

shape: (5, 2)
┌────────────────────────────────┬───────┐
│ ofns_desc                      ┆ count │
│ ---                            ┆ ---   │
│ str                            ┆ u32   │
╞════════════════════════════════╪═══════╡
│ PETIT LARCENY                  ┆ 82333 │
│ HARRASSMENT 2                  ┆ 66735 │
│ CRIMINAL MISCHIEF & RELATED OF ┆ 47289 │
│ ASSAULT 3 & RELATED OFFENSES   ┆ 43417 │
│ GRAND LARCENY                  ┆ 35573 │
└────────────────────────────────┴───────┘

In [97]:
top_5 = data.filter(
    pl.col('cmplnt_fr_dt').dt.year() == 2020
).select(
    pl.col('ofns_desc').value_counts()
).unnest().top_k(77, by='count').collect()
top_5

shape: (60, 2)
┌─────────────────────────────────┬───────┐
│ ofns_desc                       ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ PETIT LARCENY                   ┆ 82333 │
│ HARRASSMENT 2                   ┆ 66735 │
│ CRIMINAL MISCHIEF & RELATED OF  ┆ 47289 │
│ ASSAULT 3 & RELATED OFFENSES    ┆ 43417 │
│ GRAND LARCENY                   ┆ 35573 │
│ …                               ┆ …     │
│ UNLAWFUL POSS. WEAP. ON SCHOOL  ┆ 2     │
│ HOMICIDE-NEGLIGENT-VEHICLE      ┆ 2     │
│ FORTUNE TELLING                 ┆ 1     │
│ LOITERING/GAMBLING (CARDS, DIC  ┆ 1     │
│ NYS LAWS-UNCLASSIFIED VIOLATIO… ┆ 1     │
└─────────────────────────────────┴───────┘

In [98]:
data.head(5).collect()

shape: (5, 33)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ datetime[μ ┆ datetime[ ┆ i32       ┆   ┆ str       ┆ str       ┆          ┆         │
│            ┆ s]         ┆ μs]       ┆           ┆   ┆           ┆           ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 2002-01-01 ┆ 2006-02-2 ┆ null      ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆ 11:00:00   ┆ 5         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 11:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 2005-04-22 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│            ┆ 02:00:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10832306   ┆ 2005-07-11 ┆ 2006-03-2 ┆ null      ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆ 20:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 12:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 2005-10-19 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│            ┆ 20:30:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 23893731   ┆ 2005-12-04 ┆ 2006-08-0 ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆ 09:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 17:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 17 Parmi ce top 5, quels sont les tranches d'âge les plus touchées en 2020 ?

<br>

In [99]:
liste_top_5 = top_5.get_column("ofns_desc").to_list()
liste_top_5

top_5_age_2020 = (
    data
    .filter(
        (pl.col("cmplnt_fr_dt").dt.year() == 2020)
        & pl.col("ofns_desc").is_in(liste_top_5)
        & pl.col("vic_age_group").is_not_null()
    )
)

top_5_age_2020.head(5).collect()

shape: (5, 33)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ datetime[μ ┆ datetime[ ┆ i32       ┆   ┆ str       ┆ str       ┆          ┆         │
│            ┆ s]         ┆ μs]       ┆           ┆   ┆           ┆           ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 210240572  ┆ 2020-02-28 ┆ null      ┆ 106       ┆ … ┆ null      ┆ <18       ┆ BLACK    ┆ M       │
│            ┆ 15:15:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 210881300  ┆ 2020-03-10 ┆ null      ┆ 67        ┆ … ┆ null      ┆ 45-64     ┆ BLACK    ┆ M       │
│            ┆ 21:30:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 213858183  ┆ 2020-05-28 ┆ null      ┆ 43        ┆ … ┆ null      ┆ UNKNOWN   ┆ UNKNOWN  ┆ D       │
│            ┆ 08:15:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 213831383  ┆ 2020-05-31 ┆ null      ┆ 47        ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│            ┆ 13:45:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 213756171  ┆ 2020-06-01 ┆ null      ┆ 52        ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│            ┆ 16:00:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [100]:
liste_top_5 = top_5.get_column("ofns_desc").to_list()
liste_top_5

liste_top_5 = (
    data
    .filter(
        (pl.col("cmplnt_fr_dt").dt.year() == 2020)
        & pl.col("ofns_desc").is_in(liste_top_5)
        & pl.col("vic_age_group").is_not_null()
    )
)

liste_top_5.head(5).collect()

shape: (5, 33)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ datetime[μ ┆ datetime[ ┆ i32       ┆   ┆ str       ┆ str       ┆          ┆         │
│            ┆ s]         ┆ μs]       ┆           ┆   ┆           ┆           ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 210240572  ┆ 2020-02-28 ┆ null      ┆ 106       ┆ … ┆ null      ┆ <18       ┆ BLACK    ┆ M       │
│            ┆ 15:15:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 210881300  ┆ 2020-03-10 ┆ null      ┆ 67        ┆ … ┆ null      ┆ 45-64     ┆ BLACK    ┆ M       │
│            ┆ 21:30:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 213858183  ┆ 2020-05-28 ┆ null      ┆ 43        ┆ … ┆ null      ┆ UNKNOWN   ┆ UNKNOWN  ┆ D       │
│            ┆ 08:15:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 213831383  ┆ 2020-05-31 ┆ null      ┆ 47        ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│            ┆ 13:45:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 213756171  ┆ 2020-06-01 ┆ null      ┆ 52        ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│            ┆ 16:00:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [101]:
# This block groups by offense and victim age group,
# then counts the number of incidents.
top_5_age_2020 = (
    top_5_age_2020
    .group_by(
        "ofns_desc",
        "vic_age_group"
    )
    .agg(
        pl.len().alias("nombre_occurrences")
    )
)

top_5_age_2020.head(5).collect()

shape: (5, 3)
┌─────────────────────────────────┬───────────────┬────────────────────┐
│ ofns_desc                       ┆ vic_age_group ┆ nombre_occurrences │
│ ---                             ┆ ---           ┆ ---                │
│ str                             ┆ str           ┆ u32                │
╞═════════════════════════════════╪═══════════════╪════════════════════╡
│ LOITERING/GAMBLING (CARDS, DIC  ┆ UNKNOWN       ┆ 1                  │
│ HOMICIDE-NEGLIGENT-VEHICLE      ┆ 45-64         ┆ 1                  │
│ FRAUDULENT ACCOSTING            ┆ <18           ┆ 2                  │
│ NYS LAWS-UNCLASSIFIED VIOLATIO… ┆ UNKNOWN       ┆ 1                  │
│ ARSON                           ┆ 18-24         ┆ 10                 │
└─────────────────────────────────┴───────────────┴────────────────────┘

In [102]:
liste_top_5 = top_5.get_column("ofns_desc").to_list()

top_5_age_2020 = (
    data
    .filter(
        (pl.col("cmplnt_fr_dt").dt.year() == 2020)
        & pl.col("ofns_desc").is_in(liste_top_5)
        & pl.col("vic_age_group").is_not_null()
    )
    .group_by(
        "ofns_desc",
        "vic_age_group"
    )
    .agg(
        pl.len().alias("nombre_occurrences")
    )
    .sort(
        ["ofns_desc", "nombre_occurrences"],
        descending=[False, True]
    )
    .collect()
)

top_5_age_2020

shape: (285, 3)
┌──────────────────────────┬───────────────┬────────────────────┐
│ ofns_desc                ┆ vic_age_group ┆ nombre_occurrences │
│ ---                      ┆ ---           ┆ ---                │
│ str                      ┆ str           ┆ u32                │
╞══════════════════════════╪═══════════════╪════════════════════╡
│ ADMINISTRATIVE CODE      ┆ 25-44         ┆ 438                │
│ ADMINISTRATIVE CODE      ┆ 45-64         ┆ 169                │
│ ADMINISTRATIVE CODE      ┆ 18-24         ┆ 134                │
│ ADMINISTRATIVE CODE      ┆ UNKNOWN       ┆ 92                 │
│ ADMINISTRATIVE CODE      ┆ <18           ┆ 54                 │
│ …                        ┆ …             ┆ …                  │
│ VEHICLE AND TRAFFIC LAWS ┆ 18-24         ┆ 924                │
│ VEHICLE AND TRAFFIC LAWS ┆ UNKNOWN       ┆ 419                │
│ VEHICLE AND TRAFFIC LAWS ┆ 65+           ┆ 342                │
│ VEHICLE AND TRAFFIC LAWS ┆ <18           ┆ 313                │
│ VEHICLE AND TRAFFIC LAWS ┆ 1014          ┆ 1                  │
└──────────────────────────┴───────────────┴────────────────────┘

#### 18 Afficher l'évolution(en valeur absolue et en %), d'année en année, du nombre d'offenses faites aux femmes depuis 2010

<br>

In [111]:
# This block displays the distinct values of the victim sex column.
valeur_sex = data.select(
    pl.col("vic_sex").unique().sort()
).collect()

valeur_sex

shape: (7, 1)
┌─────────┐
│ vic_sex │
│ ---     │
│ str     │
╞═════════╡
│ null    │
│ D       │
│ E       │
│ F       │
│ L       │
│ M       │
│ U       │
└─────────┘

In [113]:

# This block counts offenses against female victims by year since 2010.
offenses_femmes_par_annee = (
    data
    .filter(
        (pl.col("vic_sex") == "F")
        & (pl.col("cmplnt_fr_dt").dt.year() >= 2010)
    )
    .with_columns(
        pl.col("cmplnt_fr_dt").dt.year().alias("annee")
    )
    .group_by("annee")
    .agg(
        pl.len().cast(pl.Int64).alias("nombre_offenses")
    )
    .sort("annee")
)

offenses_femmes_par_annee.collect()

shape: (13, 2)
┌───────┬─────────────────┐
│ annee ┆ nombre_offenses │
│ ---   ┆ ---             │
│ i32   ┆ i64             │
╞═══════╪═════════════════╡
│ 2010  ┆ 195190          │
│ 2011  ┆ 190783          │
│ 2012  ┆ 199699          │
│ 2013  ┆ 198328          │
│ 2014  ┆ 191673          │
│ …     ┆ …               │
│ 2018  ┆ 183579          │
│ 2019  ┆ 182541          │
│ 2020  ┆ 164231          │
│ 2021  ┆ 179505          │
│ 2022  ┆ 199058          │
└───────┴─────────────────┘

In [117]:


# This block calculates the absolute year-on-year change.
offenses_femmes_evolution = (
    offenses_femmes_par_annee
    .with_columns(
        (
            pl.col("nombre_offenses")
            - pl.col("nombre_offenses").shift(1)
        ).alias("evolution_absolue")
    )
)

offenses_femmes_evolution.collect()

shape: (13, 3)
┌───────┬─────────────────┬───────────────────┐
│ annee ┆ nombre_offenses ┆ evolution_absolue │
│ ---   ┆ ---             ┆ ---               │
│ i32   ┆ i64             ┆ i64               │
╞═══════╪═════════════════╪═══════════════════╡
│ 2010  ┆ 195190          ┆ null              │
│ 2011  ┆ 190783          ┆ -4407             │
│ 2012  ┆ 199699          ┆ 8916              │
│ 2013  ┆ 198328          ┆ -1371             │
│ 2014  ┆ 191673          ┆ -6655             │
│ …     ┆ …               ┆ …                 │
│ 2018  ┆ 183579          ┆ -210              │
│ 2019  ┆ 182541          ┆ -1038             │
│ 2020  ┆ 164231          ┆ -18310            │
│ 2021  ┆ 179505          ┆ 15274             │
│ 2022  ┆ 199058          ┆ 19553             │
└───────┴─────────────────┴───────────────────┘

In [119]:
# This block calculates the year-on-year percentage change.
offenses_femmes_evolution = (
    offenses_femmes_evolution
    .with_columns(
        (
            pl.col("evolution_absolue")
            / pl.col("nombre_offenses").shift(1)
            * 100
        )
        .round(2)
        .alias("evolution_pourcentage")
    )
)

offenses_femmes_evolution.collect()

shape: (13, 4)
┌───────┬─────────────────┬───────────────────┬───────────────────────┐
│ annee ┆ nombre_offenses ┆ evolution_absolue ┆ evolution_pourcentage │
│ ---   ┆ ---             ┆ ---               ┆ ---                   │
│ i32   ┆ i64             ┆ i64               ┆ f64                   │
╞═══════╪═════════════════╪═══════════════════╪═══════════════════════╡
│ 2010  ┆ 195190          ┆ null              ┆ null                  │
│ 2011  ┆ 190783          ┆ -4407             ┆ -2.26                 │
│ 2012  ┆ 199699          ┆ 8916              ┆ 4.67                  │
│ 2013  ┆ 198328          ┆ -1371             ┆ -0.69                 │
│ 2014  ┆ 191673          ┆ -6655             ┆ -3.36                 │
│ …     ┆ …               ┆ …                 ┆ …                     │
│ 2018  ┆ 183579          ┆ -210              ┆ -0.11                 │
│ 2019  ┆ 182541          ┆ -1038             ┆ -0.57                 │
│ 2020  ┆ 164231          ┆ -18310            ┆ -10.03                │
│ 2021  ┆ 179505          ┆ 15274             ┆ 9.3                   │
│ 2022  ┆ 199058          ┆ 19553             ┆ 10.89                 │
└───────┴─────────────────┴───────────────────┴───────────────────────┘

#### 19 Affichez le nombre d'enregistrements par jour de la semaine(*e.g.* lundi, mardi, *etc.*) et ce pour Manhattan

<br>

In [125]:
#.dt.weekday()
#.strftime

manhattan_jours = (
    data
    .filter(
        pl.col("boro_nm") == "MANHATTAN"
    )
    .with_columns(
        pl.col("cmplnt_fr_dt")
        .dt.weekday()
        .alias("jour_numero"),
        pl.col("cmplnt_fr_dt")
                .dt.strftime("%A")
                .alias("jour_semaine")
    )
    .group_by("jour_semaine", "jour_numero")
    .agg(
        pl.len().alias("nombre_enregistrements")
    )
    .collect()
)

manhattan_jours

shape: (8, 3)
┌──────────────┬─────────────┬────────────────────────┐
│ jour_semaine ┆ jour_numero ┆ nombre_enregistrements │
│ ---          ┆ ---         ┆ ---                    │
│ str          ┆ i8          ┆ u32                    │
╞══════════════╪═════════════╪════════════════════════╡
│ Friday       ┆ 5           ┆ 320524                 │
│ Tuesday      ┆ 2           ┆ 287358                 │
│ Thursday     ┆ 4           ┆ 298523                 │
│ Wednesday    ┆ 3           ┆ 297065                 │
│ Saturday     ┆ 6           ┆ 294866                 │
│ Monday       ┆ 1           ┆ 265135                 │
│ Sunday       ┆ 7           ┆ 252547                 │
│ null         ┆ null        ┆ 154                    │
└──────────────┴─────────────┴────────────────────────┘

In [129]:
# This block displays unique dates with their weekday number.
valeur_jour = (
    data
    .select(
        pl.col("cmplnt_fr_dt"),
        pl.col("cmplnt_fr_dt")
        .dt.weekday()
        .alias("jour_numero")
    )
    .unique()
    .sort("cmplnt_fr_dt")
    .collect()
)

valeur_jour

shape: (2_389_552, 2)
┌─────────────────────┬─────────────┐
│ cmplnt_fr_dt        ┆ jour_numero │
│ ---                 ┆ ---         │
│ datetime[μs]        ┆ i8          │
╞═════════════════════╪═════════════╡
│ null                ┆ null        │
│ 1010-05-20 20:00:00 ┆ 7           │
│ 1010-08-11 13:00:00 ┆ 6           │
│ 1010-08-28 13:35:00 ┆ 2           │
│ 1010-09-04 16:20:00 ┆ 2           │
│ …                   ┆ …           │
│ 2022-12-31 23:20:00 ┆ 6           │
│ 2022-12-31 23:30:00 ┆ 6           │
│ 2022-12-31 23:40:00 ┆ 6           │
│ 2022-12-31 23:50:00 ┆ 6           │
│ 2022-12-31 23:55:00 ┆ 6           │
└─────────────────────┴─────────────┘

In [131]:
# This block displays the weekday number and weekday name.
valeur_jour = (
    data
    .select(
        pl.col("cmplnt_fr_dt")
        .dt.weekday()
        .alias("jour_numero"),

        pl.col("cmplnt_fr_dt")
        .dt.strftime("%A")
        .alias("jour_semaine")
    )
    .unique()
    .sort("jour_numero")
    .collect()
)

valeur_jour

shape: (8, 2)
┌─────────────┬──────────────┐
│ jour_numero ┆ jour_semaine │
│ ---         ┆ ---          │
│ i8          ┆ str          │
╞═════════════╪══════════════╡
│ null        ┆ null         │
│ 1           ┆ Monday       │
│ 2           ┆ Tuesday      │
│ 3           ┆ Wednesday    │
│ 4           ┆ Thursday     │
│ 5           ┆ Friday       │
│ 6           ┆ Saturday     │
│ 7           ┆ Sunday       │
└─────────────┴──────────────┘

#### 20 Ajoutez une colonne aux données qui doit permettre d'identifier des moments dans les journées en fonction de l'heure

*e.g.*:
- entre 22h00 et 04h59 => NIGHT
- entre 05H00 et 18h59 => DAY
- entre 19h00 et 21h59 => EVENING

Ensuite afficher le nombre d'enregistements par période et par type d'infraction(*i.e.* law_cat_cd)

<br>

#### 21 Afin de pouvoir trier correctement le résultat de l'exercice précédent, ajoutez une colonne reprenenant le niveau de gravité:

- 1: 'FELONY'
- 2: 'MISDEMEANOR'
- 3: 'VIOLATION'

#### 22 Reprenez l'exercice précédent mais en ne gardant que les cinq dernières années disponnibles et en excluant les infractions les plus minimes

<br>

In [133]:
pl.col("cmplnt_fr_dt").dt.hour()
# This block adds a day-period column based on the complaint start hour.
data = data.with_columns(
    pl.when(
        (pl.col("cmplnt_fr_dt").dt.hour() >= 22)
        | (pl.col("cmplnt_fr_dt").dt.hour() < 5)
    )
    .then(pl.lit("NIGHT"))

    .when(
        (pl.col("cmplnt_fr_dt").dt.hour() >= 5)
        & (pl.col("cmplnt_fr_dt").dt.hour() < 19)
    )
    .then(pl.lit("DAY"))

    .otherwise(pl.lit("EVENING"))

    .alias("periode_journee")
)

In [138]:
data.select(
    "cmplnt_fr_dt",
    "periode_journee"
).head(10).collect()

shape: (10, 2)
┌─────────────────────┬─────────────────┐
│ cmplnt_fr_dt        ┆ periode_journee │
│ ---                 ┆ ---             │
│ datetime[μs]        ┆ str             │
╞═════════════════════╪═════════════════╡
│ 2002-01-01 11:00:00 ┆ DAY             │
│ 2005-04-22 02:00:00 ┆ NIGHT           │
│ 2005-07-11 20:00:00 ┆ EVENING         │
│ 2005-10-19 20:30:00 ┆ EVENING         │
│ 2005-12-04 09:00:00 ┆ DAY             │
│ 2006-01-09 21:56:00 ┆ EVENING         │
│ 2006-01-11 08:00:00 ┆ DAY             │
│ 2006-01-13 04:00:00 ┆ NIGHT           │
│ 2006-01-15 13:20:00 ┆ DAY             │
│ 2006-01-22 22:55:00 ┆ NIGHT           │
└─────────────────────┴─────────────────┘

In [139]:
# This block counts records by day period and offense category.
infractions_par_periode = (
    data
    .group_by(
        "periode_journee",
        "law_cat_cd"
    )
    .agg(
        pl.len().alias("nombre_enregistrements")
    )
    .sort(
        ["periode_journee", "nombre_enregistrements"],
        descending=[False, True]
    )
    .collect()
)

infractions_par_periode

shape: (9, 3)
┌─────────────────┬─────────────┬────────────────────────┐
│ periode_journee ┆ law_cat_cd  ┆ nombre_enregistrements │
│ ---             ┆ ---         ┆ ---                    │
│ str             ┆ str         ┆ u32                    │
╞═════════════════╪═════════════╪════════════════════════╡
│ DAY             ┆ MISDEMEANOR ┆ 2736906                │
│ DAY             ┆ FELONY      ┆ 1497981                │
│ DAY             ┆ VIOLATION   ┆ 740900                 │
│ EVENING         ┆ MISDEMEANOR ┆ 776498                 │
│ EVENING         ┆ FELONY      ┆ 400231                 │
│ EVENING         ┆ VIOLATION   ┆ 182459                 │
│ NIGHT           ┆ MISDEMEANOR ┆ 1120152                │
│ NIGHT           ┆ FELONY      ┆ 701578                 │
│ NIGHT           ┆ VIOLATION   ┆ 196344                 │
└─────────────────┴─────────────┴────────────────────────┘

In [140]:
# This block creates the day-period column.
valeur_day_time = (
    data
    .with_columns(
        pl.when(
            (pl.col("cmplnt_fr_dt").dt.hour() >= 22)
            | (pl.col("cmplnt_fr_dt").dt.hour() < 5)
        )
        .then(pl.lit("NIGHT"))

        .when(
            (pl.col("cmplnt_fr_dt").dt.hour() >= 5)
            & (pl.col("cmplnt_fr_dt").dt.hour() < 19)
        )
        .then(pl.lit("DAY"))

        .otherwise(pl.lit("EVENING"))
        .alias("periode_journee")
    )
    .select("periode_journee")
    .unique()
    .collect()
)

valeur_day_time

shape: (3, 1)
┌─────────────────┐
│ periode_journee │
│ ---             │
│ str             │
╞═════════════════╡
│ EVENING         │
│ NIGHT           │
│ DAY             │
└─────────────────┘

#### 23 Proposez un crosstab avec le nombre d'enregistrements par type d'infractions et moment de la journée

Plusieurs remarques:
- nous voudrions également avoir non pas les valeurs absolues mais les ratios. Ces ratios peuvent être calculer de trois façons:
    - en divisant chaque cellule par la somme de sa colonne
    - en divisant chaque cellule par la somme de sa ligne
    - en divisant chaque cellule par le total de la matrice
- l'exercice est plus facile à réaliser si vous passez par Pandas qui propose une solution avec crosstab. Nous voudrions que vous proposiez également une solution sans passer par Pandas.

<br>

In [141]:
# This block collects only the columns needed for the crosstab and converts them to pandas.
df_cross = (
    data
    .select(
        "law_cat_cd",
        "periode_journee"
    )
    .collect()
    .to_pandas()
)

In [143]:
import pandas as pd
# This block creates the absolute-count crosstab.
crosstab_count = pd.crosstab(
    df_cross["law_cat_cd"],
    df_cross["periode_journee"]
)

crosstab_count

periode_journee      DAY  EVENING    NIGHT
law_cat_cd
FELONY           1497981   400231   701578
MISDEMEANOR      2736906   776498  1120152
VIOLATION         740900   182459   196344

In [144]:
# This block calculates row-normalized ratios.
crosstab_ligne = pd.crosstab(
    df_cross["law_cat_cd"],
    df_cross["periode_journee"],
    normalize="index"
)

crosstab_ligne

periode_journee       DAY   EVENING     NIGHT
law_cat_cd
FELONY           0.576193  0.153947  0.269859
MISDEMEANOR      0.590671  0.167581  0.241748
VIOLATION        0.661693  0.162953  0.175354

In [145]:
# This block calculates column-normalized ratios.
crosstab_colonne = pd.crosstab(
    df_cross["law_cat_cd"],
    df_cross["periode_journee"],
    normalize="columns"
)

crosstab_colonne

periode_journee       DAY   EVENING     NIGHT
law_cat_cd
FELONY           0.301054  0.294463  0.347647
MISDEMEANOR      0.550045  0.571296  0.555060
VIOLATION        0.148901  0.134241  0.097293

In [146]:
# This block calculates ratios relative to the whole table.
crosstab_total = pd.crosstab(
    df_cross["law_cat_cd"],
    df_cross["periode_journee"],
    normalize="all"
)

crosstab_total

periode_journee       DAY   EVENING     NIGHT
law_cat_cd
FELONY           0.179333  0.047914  0.083991
MISDEMEANOR      0.327654  0.092960  0.134101
VIOLATION        0.088698  0.021843  0.023506

In [147]:
# This block counts records for each offense category and day period.
cross_long = (
    data
    .group_by(
        "law_cat_cd",
        "periode_journee"
    )
    .agg(
        pl.len().alias("nombre_enregistrements")
    )
)

In [148]:
# This block pivots the long-format counts into a crosstab.
cross_polars = (
    cross_long
    .collect()
    .pivot(
        values="nombre_enregistrements",
        index="law_cat_cd",
        on="periode_journee"
    )
)

cross_polars

shape: (3, 4)
┌─────────────┬─────────┬─────────┬─────────┐
│ law_cat_cd  ┆ NIGHT   ┆ EVENING ┆ DAY     │
│ ---         ┆ ---     ┆ ---     ┆ ---     │
│ str         ┆ u32     ┆ u32     ┆ u32     │
╞═════════════╪═════════╪═════════╪═════════╡
│ FELONY      ┆ 701578  ┆ 400231  ┆ 1497981 │
│ VIOLATION   ┆ 196344  ┆ 182459  ┆ 740900  │
│ MISDEMEANOR ┆ 1120152 ┆ 776498  ┆ 2736906 │
└─────────────┴─────────┴─────────┴─────────┘

In [149]:
import pandas as pd
# This block creates the absolute-count crosstab.
crosstab_count = pd.crosstab(
    df_cross["law_cat_cd"],
    df_cross["periode_journee"]
)

crosstab_count

periode_journee      DAY  EVENING    NIGHT
law_cat_cd
FELONY           1497981   400231   701578
MISDEMEANOR      2736906   776498  1120152
VIOLATION         740900   182459   196344

In [150]:
# This block calculates ratios across each row.
cross_ratio_ligne = (
    cross_polars
    .with_columns(
        (
            pl.col("DAY")
            / pl.sum_horizontal(
                pl.col("DAY"),
                pl.col("EVENING"),
                pl.col("NIGHT")
            )
        ).alias("DAY_ratio"),

        (
            pl.col("EVENING")
            / pl.sum_horizontal(
                pl.col("DAY"),
                pl.col("EVENING"),
                pl.col("NIGHT")
            )
        ).alias("EVENING_ratio"),

        (
            pl.col("NIGHT")
            / pl.sum_horizontal(
                pl.col("DAY"),
                pl.col("EVENING"),
                pl.col("NIGHT")
            )
        ).alias("NIGHT_ratio")
    )
)

cross_ratio_ligne

shape: (3, 7)
┌─────────────┬─────────┬─────────┬─────────┬───────────┬───────────────┬─────────────┐
│ law_cat_cd  ┆ NIGHT   ┆ EVENING ┆ DAY     ┆ DAY_ratio ┆ EVENING_ratio ┆ NIGHT_ratio │
│ ---         ┆ ---     ┆ ---     ┆ ---     ┆ ---       ┆ ---           ┆ ---         │
│ str         ┆ u32     ┆ u32     ┆ u32     ┆ f64       ┆ f64           ┆ f64         │
╞═════════════╪═════════╪═════════╪═════════╪═══════════╪═══════════════╪═════════════╡
│ FELONY      ┆ 701578  ┆ 400231  ┆ 1497981 ┆ 0.576193  ┆ 0.153947      ┆ 0.269859    │
│ VIOLATION   ┆ 196344  ┆ 182459  ┆ 740900  ┆ 0.661693  ┆ 0.162953      ┆ 0.175354    │
│ MISDEMEANOR ┆ 1120152 ┆ 776498  ┆ 2736906 ┆ 0.590671  ┆ 0.167581      ┆ 0.241748    │
└─────────────┴─────────┴─────────┴─────────┴───────────┴───────────────┴─────────────┘

In [152]:
# This block calculates ratios relative to each column total.
cross_ratio_colonne = (
    cross_polars
    .with_columns(
        (pl.col("DAY") / pl.col("DAY").sum()).alias("DAY_ratio"),
        (pl.col("EVENING") / pl.col("EVENING").sum()).alias("EVENING_ratio"),
        (pl.col("NIGHT") / pl.col("NIGHT").sum()).alias("NIGHT_ratio")
    )
)

cross_ratio_colonne

shape: (3, 7)
┌─────────────┬─────────┬─────────┬─────────┬───────────┬───────────────┬─────────────┐
│ law_cat_cd  ┆ NIGHT   ┆ EVENING ┆ DAY     ┆ DAY_ratio ┆ EVENING_ratio ┆ NIGHT_ratio │
│ ---         ┆ ---     ┆ ---     ┆ ---     ┆ ---       ┆ ---           ┆ ---         │
│ str         ┆ u32     ┆ u32     ┆ u32     ┆ f64       ┆ f64           ┆ f64         │
╞═════════════╪═════════╪═════════╪═════════╪═══════════╪═══════════════╪═════════════╡
│ FELONY      ┆ 701578  ┆ 400231  ┆ 1497981 ┆ 0.301054  ┆ 0.294463      ┆ 0.347647    │
│ VIOLATION   ┆ 196344  ┆ 182459  ┆ 740900  ┆ 0.148901  ┆ 0.134241      ┆ 0.097293    │
│ MISDEMEANOR ┆ 1120152 ┆ 776498  ┆ 2736906 ┆ 0.550045  ┆ 0.571296      ┆ 0.55506     │
└─────────────┴─────────┴─────────┴─────────┴───────────┴───────────────┴─────────────┘

In [154]:
# This block calculates the grand total of all crosstab cells.
total_general = (
    cross_polars
    .select(
        pl.sum_horizontal(
            pl.col("DAY"),
            pl.col("EVENING"),
            pl.col("NIGHT")
        ).sum()
    )
    .item()
)

In [155]:
# This block calculates each cell's share of the whole matrix.
cross_ratio_total = (
    cross_polars
    .with_columns(
        (pl.col("DAY") / total_general).alias("DAY_ratio"),
        (pl.col("EVENING") / total_general).alias("EVENING_ratio"),
        (pl.col("NIGHT") / total_general).alias("NIGHT_ratio")
    )
)

cross_ratio_total

shape: (3, 7)
┌─────────────┬─────────┬─────────┬─────────┬───────────┬───────────────┬─────────────┐
│ law_cat_cd  ┆ NIGHT   ┆ EVENING ┆ DAY     ┆ DAY_ratio ┆ EVENING_ratio ┆ NIGHT_ratio │
│ ---         ┆ ---     ┆ ---     ┆ ---     ┆ ---       ┆ ---           ┆ ---         │
│ str         ┆ u32     ┆ u32     ┆ u32     ┆ f64       ┆ f64           ┆ f64         │
╞═════════════╪═════════╪═════════╪═════════╪═══════════╪═══════════════╪═════════════╡
│ FELONY      ┆ 701578  ┆ 400231  ┆ 1497981 ┆ 0.179333  ┆ 0.047914      ┆ 0.083991    │
│ VIOLATION   ┆ 196344  ┆ 182459  ┆ 740900  ┆ 0.088698  ┆ 0.021843      ┆ 0.023506    │
│ MISDEMEANOR ┆ 1120152 ┆ 776498  ┆ 2736906 ┆ 0.327654  ┆ 0.09296       ┆ 0.134101    │
└─────────────┴─────────┴─────────┴─────────┴───────────┴───────────────┴─────────────┘

#### 24 Identifiez les offenses qui ont connu, en moyenne, la plus grande progression sur les 10 dernières années disponnibles

**Compléments d'informations**: nous voulons pour chaque offense et pour chaque année avoir son nombre d'occurences et afficher sa progression par rapport à n-1 et ensuite faire une moyenne sur ces progressions.

<br>

#### 25 Filtrez afin de ne garder que les offenses avec au minimum 1000 enregistrements

##### 25.1 Affichez également le top et bottom 10

<br>

#### 26 A l'aide d'une fenêtre, identifiez les moments dans la journée et dans l'année qui répertorient le plus de plaintes

<br>

#### 26.1 Pouvez-vous constater une différence entre les différentes gravités de crimes ? Certains crimes ont-ils tendance a plus être commis à telle ou telle heure de la journée ?

<br>

#### 27 Et quelle est la période dans l'année la plus propice ?

<br>