# Exercices Polars

La série suivante d'exercices doit vous permettre de maîtriser les rudiments de Polars. Elle présupose que vous ayez déjà les bases avec Pandas et SQL.

Toutes les fonctions et méthodes nécessaires à cette série n'ont bien évidemment été pas abordées durant la session théorique et ces exercices vous forceront à trouver des pistes de solution dans la [documentation](https://www.pola.rs/) officielle.

Soyez curieux et n'hésitez pas à aller plus loin que les énoncés et à analyser plus en profondeur le dataset proposé.

**Conseil:** Si des exercices vous résistent, fragmentez votre problème en petits morceaux. N'hésitez pas à lister les différentes étapes nécessaire à l'élaboration des exercices avant de vous lancer dans le code.

<br>

#### 1 Procurez-vous le fichier [ici](https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i) et affichez les 5 premières lignes

**Conseil:** avant d'aller plus loin, prenez le temps de lire les informations présentes afin de bien comprendre les données avec lesquelles vous travaillerez.


https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i/about_data

<br>

In [ ]:
import polars as pl
file_path = "data/data_exo/data/NYPD_complaints_all.csv"
data = pl.scan_csv(
    file_path, infer_schema_length=100000
    , null_values=["", "NA", "NaN", "null", "NULL", '(null)']
    )

data.head(20).collect()

shape: (20, 35)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE  ┆ VIC_SEX │
│ ---        ┆ _DT       ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---       ┆ ---     │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str     │
│            ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆           ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 10600119   ┆ 01/01/200 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ null      ┆ 18-24     ┆ WHITE     ┆ F       │
│            ┆ 2         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆         │
│ 11052575   ┆ 04/22/200 ┆ 02:00:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK     ┆ M       │
│            ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 10832306   ┆ 07/11/200 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ null      ┆ 45-64     ┆ WHITE     ┆ M       │
│            ┆ 5         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆         │
│ 10107192   ┆ 10/19/200 ┆ 20:30:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK     ┆ F       │
│            ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 23893731   ┆ 12/04/200 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 5         ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ 10376282   ┆ 02/06/200 ┆ 22:15:00  ┆ null      ┆ … ┆ null      ┆ 18-24     ┆ WHITE     ┆ F       │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ HISPANIC  ┆         │
│ 10344917   ┆ 02/08/200 ┆ 08:30:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ HISPANIC  ┆         │
│ 10361314   ┆ 02/11/200 ┆ 16:35:00  ┆ null      ┆ … ┆ null      ┆ 45-64     ┆ BLACK     ┆ F       │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 10363948   ┆ 02/11/200 ┆ 17:15:00  ┆ null      ┆ … ┆ null      ┆ 18-24     ┆ BLACK     ┆ F       │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 10608850   ┆ 02/13/200 ┆ 09:00:00  ┆ null      ┆ … ┆ null      ┆ null      ┆ UNKNOWN   ┆ D       │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

#### 2 Affichez le nombre de lignes, de colonnes, le schéma ainsi que le poids total du fichier en mémoire

<br>

In [2]:
data.select(pl.len()).collect()
len(data.collect_schema())
data.collect().estimated_size(unit='mb')

2512.9604539871216

#### 3 Affichez le nombre et la proportion de valeurs manquantes par colonne et pour le dataset au complet

<br>

In [3]:
#%%timeit
data.null_count().collect()

shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 48        ┆ 1778361   ┆ … ┆ 8169741   ┆ 1623390   ┆ 561      ┆ 308     │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [4]:
#%%timeit
data.select(pl.all().is_null()).collect().sum()

shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 48        ┆ 1778361   ┆ … ┆ 8169741   ┆ 1623390   ┆ 561      ┆ 308     │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [5]:
n_rows = data.select(pl.len()).collect()
display(n_rows)
n_rows.get_column('len')[0]

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 8353049 │
└─────────┘

8353049

In [6]:
n_rows = data.select(pl.len()).collect().get_column('len')[0]
nulls_count = data.null_count().collect()

display(nulls_count)

nulls_count\
    .transpose(
        include_header=True, header_name='column_name'
        , column_names=['null_count']
    )\
    .with_columns(
        null_ratio = pl.col('null_count')/n_rows
    ).sort('null_count', descending=True)

shape: (1, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ u32        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32     │
│            ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 0          ┆ 655        ┆ 48        ┆ 1778361   ┆ … ┆ 8169741   ┆ 1623390   ┆ 561      ┆ 308     │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

shape: (35, 3)
┌───────────────────┬────────────┬────────────┐
│ column_name       ┆ null_count ┆ null_ratio │
│ ---               ┆ ---        ┆ ---        │
│ str               ┆ u32        ┆ f64        │
╞═══════════════════╪════════════╪════════════╡
│ HADEVELOPT        ┆ 8323205    ┆ 0.996427   │
│ PARKS_NM          ┆ 8318817    ┆ 0.995902   │
│ TRANSIT_DISTRICT  ┆ 8169741    ┆ 0.978055   │
│ STATION_NAME      ┆ 8169741    ┆ 0.978055   │
│ HOUSING_PSA       ┆ 7719467    ┆ 0.92415    │
│ …                 ┆ …          ┆ …          │
│ RPT_DT            ┆ 0          ┆ 0.0        │
│ KY_CD             ┆ 0          ┆ 0.0        │
│ LAW_CAT_CD        ┆ 0          ┆ 0.0        │
│ JURIS_DESC        ┆ 0          ┆ 0.0        │
│ JURISDICTION_CODE ┆ 0          ┆ 0.0        │
└───────────────────┴────────────┴────────────┘

#### 4 Pour vous simplifier la vie avec le reste des exercices, mettez en minuscule le nom des colonnes

#### 4.1 Pensez également à convertir les colonnes qui devraient être en DateTime et éventuellement à regrouper les parties Date et Time

#### 4.2 Retirez les colonnes 'cmplnt_fr_tm' et 'cmplnt_to_tm' puisque vous avez tout regroupé dans une seule et même colonne

<br>

In [7]:
data.head(5).collect()

shape: (5, 35)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ CMPLNT_NUM ┆ CMPLNT_FR_ ┆ CMPLNT_FR ┆ CMPLNT_TO ┆ … ┆ STATION_N ┆ VIC_AGE_G ┆ VIC_RACE ┆ VIC_SEX │
│ ---        ┆ DT         ┆ _TM       ┆ _DT       ┆   ┆ AME       ┆ ROUP      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ str        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 01/01/2002 ┆ 11:00:00  ┆ 02/25/200 ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 04/22/2005 ┆ 02:00:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│ 10832306   ┆ 07/11/2005 ┆ 20:00:00  ┆ 03/29/200 ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 10/19/2005 ┆ 20:30:00  ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│ 23893731   ┆ 12/04/2005 ┆ 09:00:00  ┆ 08/09/200 ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [8]:
# CMPLNT_FR_DT	CMPLNT_FR_TM	CMPLNT_TO_DT	CMPLNT_TO_TM
# .str.to_datetime(format='%m/%d/%Y')
data = data.select(pl.all().name.to_lowercase())\
    .with_columns(
        cmplnt_fr_dt = pl.concat_str(
            [pl.col('cmplnt_fr_dt'), pl.col('cmplnt_fr_tm')]
            , separator=' '
        ).str.to_datetime(format='%m/%d/%Y %H:%M:%S')
        , cmplnt_to_dt = pl.concat_str(
            [pl.col('cmplnt_to_dt'), pl.col('cmplnt_to_tm')]
            , separator=' '
        ).str.to_datetime(format='%m/%d/%Y %H:%M:%S')
    ).select(pl.exclude('cmplnt_fr_tm', 'cmplnt_to_tm'))

data.head(5).collect()

shape: (5, 33)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ datetime[μ ┆ datetime[ ┆ i64       ┆   ┆ str       ┆ str       ┆          ┆         │
│            ┆ s]         ┆ μs]       ┆           ┆   ┆           ┆           ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 2002-01-01 ┆ 2006-02-2 ┆ null      ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆ 11:00:00   ┆ 5         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 11:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 2005-04-22 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│            ┆ 02:00:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10832306   ┆ 2005-07-11 ┆ 2006-03-2 ┆ null      ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆ 20:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 12:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 2005-10-19 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│            ┆ 20:30:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 23893731   ┆ 2005-12-04 ┆ 2006-08-0 ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆ 09:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 17:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 5 Vérifiez si les colonnes en Int64 peuvent être converties en Int32 afin de gagner en espace mémoire

<br>

In [9]:
import numpy as np
np.array([1, 256, 257, 1000]).astype(np.uint8)

array([  1,   0,   1, 232], dtype=uint8)

In [10]:
1000%256

232

In [11]:
overflow = pl.DataFrame(
    {
        'values': [1, 256, 257, 1000]
    }
)
display(overflow)
overflow.cast({'values': pl.UInt8}, strict=False)

shape: (4, 1)
┌────────┐
│ values │
│ ---    │
│ i64    │
╞════════╡
│ 1      │
│ 256    │
│ 257    │
│ 1000   │
└────────┘

shape: (4, 1)
┌────────┐
│ values │
│ ---    │
│ u8     │
╞════════╡
│ 1      │
│ null   │
│ null   │
│ null   │
└────────┘

In [12]:
data = data.cast({pl.Int64: pl.Int32})
data.collect_schema()

Schema([('cmplnt_num', String),
        ('cmplnt_fr_dt', Datetime(time_unit='us', time_zone=None)),
        ('cmplnt_to_dt', Datetime(time_unit='us', time_zone=None)),
        ('addr_pct_cd', Int32),
        ('rpt_dt', String),
        ('ky_cd', Int32),
        ('ofns_desc', String),
        ('pd_cd', Int32),
        ('pd_desc', String),
        ('crm_atpt_cptd_cd', String),
        ('law_cat_cd', String),
        ('boro_nm', String),
        ('loc_of_occur_desc', String),
        ('prem_typ_desc', String),
        ('juris_desc', String),
        ('jurisdiction_code', Int32),
        ('parks_nm', String),
        ('hadevelopt', String),
        ('housing_psa', Int32),
        ('x_coord_cd', Int32),
        ('y_coord_cd', Int32),
        ('susp_age_group', String),
        ('susp_race', String),
        ('susp_sex', String),
        ('transit_district', Int32),
        ('latitude', Float64),
        ('longitude', Float64),
        ('lat_lon', String),
        ('patrol_boro', String),
        ('station_name', String),
        ('vic_age_group', String),
        ('vic_race', String),
        ('vic_sex', String)])

In [13]:
data.collect().estimated_size(unit='mb')

2130.2271013259888

#### 6 Sauvez toutes vos modifications faites en un format parquet et vérifiez le résultat

<br>

In [14]:
data.sink_parquet('data/data_cleaned.parquet')

In [15]:
data = pl.scan_parquet('data/data_cleaned.parquet')
data.head(5).collect()

shape: (5, 33)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr_ ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race ┆ vic_sex │
│ ---        ┆ dt         ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---      ┆ ---     │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ str     │
│            ┆ datetime[μ ┆ datetime[ ┆ i32       ┆   ┆ str       ┆ str       ┆          ┆         │
│            ┆ s]         ┆ μs]       ┆           ┆   ┆           ┆           ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 10600119   ┆ 2002-01-01 ┆ 2006-02-2 ┆ null      ┆ … ┆ null      ┆ 18-24     ┆ WHITE    ┆ F       │
│            ┆ 11:00:00   ┆ 5         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 11:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 11052575   ┆ 2005-04-22 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ M       │
│            ┆ 02:00:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10832306   ┆ 2005-07-11 ┆ 2006-03-2 ┆ null      ┆ … ┆ null      ┆ 45-64     ┆ WHITE    ┆ M       │
│            ┆ 20:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 12:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
│ 10107192   ┆ 2005-10-19 ┆ null      ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ BLACK    ┆ F       │
│            ┆ 20:30:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 23893731   ┆ 2005-12-04 ┆ 2006-08-0 ┆ null      ┆ … ┆ null      ┆ 25-44     ┆ WHITE    ┆ F       │
│            ┆ 09:00:00   ┆ 9         ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆            ┆ 17:00:00  ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

#### 7 Affichez les 5 premières lignes des colonnes 'ofns_desc' et 'pd_desc'

<br>

In [16]:
data.select(pl.col('ofns_desc', 'pd_desc')).head(5).collect()

shape: (5, 2)
┌────────────────────────────────┬─────────────────────────────────┐
│ ofns_desc                      ┆ pd_desc                         │
│ ---                            ┆ ---                             │
│ str                            ┆ str                             │
╞════════════════════════════════╪═════════════════════════════════╡
│ RAPE                           ┆ RAPE 1                          │
│ GRAND LARCENY OF MOTOR VEHICLE ┆ LARCENY,GRAND OF AUTO           │
│ UNAUTHORIZED USE OF A VEHICLE  ┆ UNAUTHORIZED USE VEHICLE 3      │
│ MISCELLANEOUS PENAL LAW        ┆ UNAUTHORIZED USE VEHICLE 2      │
│ GRAND LARCENY                  ┆ LARCENY,GRAND BY THEFT OF CRED… │
└────────────────────────────────┴─────────────────────────────────┘

#### 8 Afficher le nombre d'incidents recensés pour le quartier de Manhattan

<br>

In [17]:
#%%timeit
data.select(pl.col('boro_nm'))\
    .filter(pl.col('boro_nm') == 'MANHATTAN')\
    .select(pl.len())\
    .collect()

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 2016172 │
└─────────┘

In [18]:
#%%timeit
data.select(pl.col('boro_nm'))\
    .filter(pl.col('boro_nm') == 'MANHATTAN')\
    .count()\
    .collect()

shape: (1, 1)
┌─────────┐
│ boro_nm │
│ ---     │
│ u32     │
╞═════════╡
│ 2016172 │
└─────────┘

#### 9 Est-ce que des  patrouilles du quartier de Brooklyn ou du Queens peuvent intervenir à Manhattan ?

<br>

In [19]:
# boro_nm = 'MANHATTAN' & patrol_bora == 
data.filter(
    (pl.col('boro_nm') == 'MANHATTAN')
    & (
        pl.col('patrol_boro').str.contains('BKLYN')
        | pl.col('patrol_boro').str.contains('QUEENS')
    )
).select(pl.col('boro_nm', 'patrol_boro')).unique().collect()

shape: (4, 2)
┌───────────┬──────────────────────────┐
│ boro_nm   ┆ patrol_boro              │
│ ---       ┆ ---                      │
│ str       ┆ str                      │
╞═══════════╪══════════════════════════╡
│ MANHATTAN ┆ PATROL BORO BKLYN SOUTH  │
│ MANHATTAN ┆ PATROL BORO QUEENS NORTH │
│ MANHATTAN ┆ PATROL BORO QUEENS SOUTH │
│ MANHATTAN ┆ PATROL BORO BKLYN NORTH  │
└───────────┴──────────────────────────┘

#### 10 Renseignez-vous sur la notion de precinct (colonne addr_pct_cd). Combien en comptabilisez-vous ?

<br>

In [20]:
data.select(pl.col('addr_pct_cd')).head(5).collect()
# This block displays all distinct non-null precinct codes, sorted increasingly.

shape: (5, 1)
┌─────────────┐
│ addr_pct_cd │
│ ---         │
│ i32         │
╞═════════════╡
│ null        │
│ null        │
│ null        │
│ null        │
│ null        │
└─────────────┘

In [21]:
# This block counts the number of distinct non-null precinct codes in addr_pct_cd.
nb_precincts = (
    data
    .filter(pl.col("addr_pct_cd").is_not_null())
    .select(
        pl.col("addr_pct_cd").n_unique().alias("nb_precincts")
    )
    .collect()
)

nb_precincts

shape: (1, 1)
┌──────────────┐
│ nb_precincts │
│ ---          │
│ u32          │
╞══════════════╡
│ 77           │
└──────────────┘

In [22]:
precincts = (
    data
    .filter(pl.col("addr_pct_cd").is_not_null())
    .select("addr_pct_cd")
    .unique()
    .sort("addr_pct_cd")
    .collect()
)

precincts

shape: (77, 1)
┌─────────────┐
│ addr_pct_cd │
│ ---         │
│ i32         │
╞═════════════╡
│ 1           │
│ 5           │
│ 6           │
│ 7           │
│ 9           │
│ …           │
│ 115         │
│ 120         │
│ 121         │
│ 122         │
│ 123         │
└─────────────┘

Un precinct correspond à une zone locale de police. La colonne addr_pct_cd indique le code du precinct associé à l’adresse de l’incident. Après exclusion des valeurs nulles, le dataset contient 77 precincts distincts.

In [23]:
# This block checks how many boroughs are associated with each precinct code.
data.filter(
    pl.col("addr_pct_cd").is_not_null()
).group_by(
    "addr_pct_cd"
).agg(
    pl.col("boro_nm").n_unique().alias("nb_boroughs"),
    pl.col("boro_nm").unique().alias("boroughs")
).sort(
    "addr_pct_cd"
).collect()

shape: (77, 3)
┌─────────────┬─────────────┬─────────────────────────────────┐
│ addr_pct_cd ┆ nb_boroughs ┆ boroughs                        │
│ ---         ┆ ---         ┆ ---                             │
│ i32         ┆ u32         ┆ list[str]                       │
╞═════════════╪═════════════╪═════════════════════════════════╡
│ 1           ┆ 6           ┆ ["MANHATTAN", null, … "BRONX"]  │
│ 5           ┆ 6           ┆ ["MANHATTAN", "BROOKLYN", … "B… │
│ 6           ┆ 5           ┆ ["MANHATTAN", "BROOKLYN", … "B… │
│ 7           ┆ 5           ┆ ["MANHATTAN", "STATEN ISLAND",… │
│ 9           ┆ 5           ┆ ["MANHATTAN", "BROOKLYN", … "Q… │
│ …           ┆ …           ┆ …                               │
│ 115         ┆ 6           ┆ ["QUEENS", null, … "BROOKLYN"]  │
│ 120         ┆ 6           ┆ ["STATEN ISLAND", null, … "BRO… │
│ 121         ┆ 4           ┆ ["STATEN ISLAND", "MANHATTAN",… │
│ 122         ┆ 5           ┆ ["STATEN ISLAND", "BROOKLYN", … │
│ 123         ┆ 5           ┆ ["STATEN ISLAND", null, … "MAN… │
└─────────────┴─────────────┴─────────────────────────────────┘

In [24]:
# This block lists each precinct and all borough values associated with it.
precincts_boroughs = (
    data
    .filter(
        pl.col("addr_pct_cd").is_not_null()
        & pl.col("boro_nm").is_not_null()
    )
    .group_by("addr_pct_cd")
    .agg(
        pl.col("boro_nm").unique().alias("boroughs"),
        pl.col("boro_nm").n_unique().alias("nb_boroughs")
    )
    .sort("addr_pct_cd")
    .collect()
)

precincts_boroughs

shape: (77, 3)
┌─────────────┬─────────────────────────────────┬─────────────┐
│ addr_pct_cd ┆ boroughs                        ┆ nb_boroughs │
│ ---         ┆ ---                             ┆ ---         │
│ i32         ┆ list[str]                       ┆ u32         │
╞═════════════╪═════════════════════════════════╪═════════════╡
│ 1           ┆ ["MANHATTAN", "STATEN ISLAND",… ┆ 5           │
│ 5           ┆ ["MANHATTAN", "BROOKLYN", … "B… ┆ 5           │
│ 6           ┆ ["MANHATTAN", "BROOKLYN", … "B… ┆ 4           │
│ 7           ┆ ["MANHATTAN", "STATEN ISLAND",… ┆ 4           │
│ 9           ┆ ["MANHATTAN", "BROOKLYN", … "Q… ┆ 4           │
│ …           ┆ …                               ┆ …           │
│ 115         ┆ ["QUEENS", "MANHATTAN", … "BRO… ┆ 5           │
│ 120         ┆ ["STATEN ISLAND", "QUEENS", … … ┆ 5           │
│ 121         ┆ ["STATEN ISLAND", "MANHATTAN",… ┆ 4           │
│ 122         ┆ ["STATEN ISLAND", "BROOKLYN", … ┆ 4           │
│ 123         ┆ ["STATEN ISLAND", "QUEENS", … … ┆ 4           │
└─────────────┴─────────────────────────────────┴─────────────┘

#### 11 A quand remonte le dernier incident rapportant un avortement ?

<br>

In [25]:
# This block finds all string columns in the LazyFrame schema.
string_cols = [
    column_name
    for column_name, dtype in data.collect_schema().items()
    if dtype == pl.String
]

In [26]:
# This block searches all rows where any string column contains "abortion".
abortion_rows_all_columns = (
    data
    .filter(
        pl.any_horizontal(
            *[
                pl.col(col).str.to_lowercase().str.contains("abortion", literal=True).fill_null(False)
                for col in string_cols
            ]
        )
    )
    .collect()
)

abortion_rows_all_columns

shape: (9, 33)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ cmplnt_num ┆ cmplnt_fr ┆ cmplnt_to ┆ addr_pct_ ┆ … ┆ station_n ┆ vic_age_g ┆ vic_race  ┆ vic_sex │
│ ---        ┆ _dt       ┆ _dt       ┆ cd        ┆   ┆ ame       ┆ roup      ┆ ---       ┆ ---     │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str     │
│            ┆ datetime[ ┆ datetime[ ┆ i32       ┆   ┆ str       ┆ str       ┆           ┆         │
│            ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 26143450   ┆ 2007-01-0 ┆ 2007-01-0 ┆ 104       ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 7         ┆ 7         ┆           ┆   ┆           ┆           ┆ HISPANIC  ┆         │
│            ┆ 19:30:00  ┆ 19:46:00  ┆           ┆   ┆           ┆           ┆           ┆         │
│ 33677689   ┆ 2007-08-0 ┆ 2007-08-0 ┆ 120       ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 14:15:00  ┆ 14:30:00  ┆           ┆   ┆           ┆           ┆           ┆         │
│ 34672117   ┆ 2007-09-2 ┆ null      ┆ 120       ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 20:43:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ 44717528   ┆ 2008-03-1 ┆ 2008-03-1 ┆ 107       ┆ … ┆ null      ┆ 25-44     ┆ BLACK     ┆ F       │
│            ┆ 0         ┆ 1         ┆           ┆   ┆           ┆           ┆ HISPANIC  ┆         │
│            ┆ 12:01:00  ┆ 07:13:00  ┆           ┆   ┆           ┆           ┆           ┆         │
│ 144122405  ┆ 2015-02-0 ┆ 2015-02-0 ┆ 106       ┆ … ┆ null      ┆ 18-24     ┆ ASIAN /   ┆ F       │
│            ┆ 6         ┆ 6         ┆           ┆   ┆           ┆           ┆ PACIFIC   ┆         │
│            ┆ 19:00:00  ┆ 19:30:00  ┆           ┆   ┆           ┆           ┆ ISLANDER  ┆         │
│ 145612418  ┆ 2015-08-2 ┆ 2015-08-2 ┆ 101       ┆ … ┆ null      ┆ 18-24     ┆ BLACK     ┆ F       │
│            ┆ 4         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 21:25:00  ┆ 21:35:00  ┆           ┆   ┆           ┆           ┆           ┆         │
│ 188019703  ┆ 2013-06-0 ┆ 2013-06-0 ┆ 68        ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 08:00:00  ┆ 08:30:00  ┆           ┆   ┆           ┆           ┆           ┆         │
│ 171447942  ┆ 2017-10-0 ┆ 2017-10-1 ┆ 114       ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 9         ┆ 2         ┆           ┆   ┆           ┆           ┆ HISPANIC  ┆         │
│            ┆ 12:00:00  ┆ 10:00:00  ┆           ┆   ┆           ┆           ┆           ┆         │
│ 182478288  ┆ 2018-04-2 ┆ null      ┆ 46        ┆ … ┆ null      ┆ 25-44     ┆ WHITE     ┆ F       │
│            ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ HISPANIC  ┆         │
│            ┆ 23:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [27]:
data.collect_schema()

Schema([('cmplnt_num', String),
        ('cmplnt_fr_dt', Datetime(time_unit='us', time_zone=None)),
        ('cmplnt_to_dt', Datetime(time_unit='us', time_zone=None)),
        ('addr_pct_cd', Int32),
        ('rpt_dt', String),
        ('ky_cd', Int32),
        ('ofns_desc', String),
        ('pd_cd', Int32),
        ('pd_desc', String),
        ('crm_atpt_cptd_cd', String),
        ('law_cat_cd', String),
        ('boro_nm', String),
        ('loc_of_occur_desc', String),
        ('prem_typ_desc', String),
        ('juris_desc', String),
        ('jurisdiction_code', Int32),
        ('parks_nm', String),
        ('hadevelopt', String),
        ('housing_psa', Int32),
        ('x_coord_cd', Int32),
        ('y_coord_cd', Int32),
        ('susp_age_group', String),
        ('susp_race', String),
        ('susp_sex', String),
        ('transit_district', Int32),
        ('latitude', Float64),
        ('longitude', Float64),
        ('lat_lon', String),
        ('patrol_boro', String),
        ('station_name', String),
        ('vic_age_group', String),
        ('vic_race', String),
        ('vic_sex', String)])

In [28]:
# This block searches all rows where the word "abortion" appears
# in either the offense description or the police description.
abortion_rows = (
    data
    .filter(
        pl.col("ofns_desc").str.to_lowercase().str.contains("abortion", literal=True).fill_null(False)
        |
        pl.col("pd_desc").str.to_lowercase().str.contains("abortion", literal=True).fill_null(False)
    )
    .select(
        "cmplnt_num",
        "rpt_dt",
        "ofns_desc",
        "pd_desc",
        "boro_nm",
        "crm_atpt_cptd_cd"
    )
    .collect()
)

abortion_rows

shape: (9, 6)
┌────────────┬────────────┬──────────────────┬──────────────────┬───────────────┬──────────────────┐
│ cmplnt_num ┆ rpt_dt     ┆ ofns_desc        ┆ pd_desc          ┆ boro_nm       ┆ crm_atpt_cptd_cd │
│ ---        ┆ ---        ┆ ---              ┆ ---              ┆ ---           ┆ ---              │
│ str        ┆ str        ┆ str              ┆ str              ┆ str           ┆ str              │
╞════════════╪════════════╪══════════════════╪══════════════════╪═══════════════╪══════════════════╡
│ 26143450   ┆ 01/07/2007 ┆ ABORTION         ┆ ABORTION 1       ┆ QUEENS        ┆ ATTEMPTED        │
│ 33677689   ┆ 08/09/2007 ┆ SEX CRIMES       ┆ ABORTIONAL       ┆ STATEN ISLAND ┆ COMPLETED        │
│            ┆            ┆                  ┆ ARTICLES,ISSUING ┆               ┆                  │
│ 34672117   ┆ 09/26/2007 ┆ ABORTION         ┆ ABORTION 1       ┆ STATEN ISLAND ┆ COMPLETED        │
│ 44717528   ┆ 03/20/2008 ┆ OFFENSES AGAINST ┆ ABORTION 2, 1,   ┆ QUEENS        ┆ COMPLETED        │
│            ┆            ┆ THE PERSON       ┆ SELF             ┆               ┆                  │
│ 144122405  ┆ 06/29/2015 ┆ ABORTION         ┆ ABORTION 1       ┆ QUEENS        ┆ COMPLETED        │
│ 145612418  ┆ 08/24/2015 ┆ ABORTION         ┆ ABORTION 1       ┆ QUEENS        ┆ ATTEMPTED        │
│ 188019703  ┆ 09/25/2018 ┆ ABORTION         ┆ ABORTION 1       ┆ BROOKLYN      ┆ COMPLETED        │
│ 171447942  ┆ 11/09/2017 ┆ ABORTION         ┆ ABORTION 1       ┆ QUEENS        ┆ COMPLETED        │
│ 182478288  ┆ 05/08/2018 ┆ ABORTION         ┆ ABORTION 1       ┆ BRONX         ┆ COMPLETED        │
└────────────┴────────────┴──────────────────┴──────────────────┴───────────────┴──────────────────┘

In [29]:
# This block counts the number of rows mentioning abortion.
abortion_rows.height

9

In [30]:
# This block creates a filter for rows where "abortion" appears in offense or police description.
abortion_filter = (
    pl.col("ofns_desc").str.to_lowercase().str.contains("abortion", literal=True).fill_null(False)
    |
    pl.col("pd_desc").str.to_lowercase().str.contains("abortion", literal=True).fill_null(False)
)

In [31]:
# This block finds the latest reported date for abortion-related incidents.
latest_abortion_date = (
    data
    .filter(abortion_filter)
    .select(
        pl.col("rpt_dt").max().alias("latest_abortion_report_date")
    )
    .collect()
)

latest_abortion_date

shape: (1, 1)
┌─────────────────────────────┐
│ latest_abortion_report_date │
│ ---                         │
│ str                         │
╞═════════════════════════════╡
│ 11/09/2017                  │
└─────────────────────────────┘

#### 12  En moyenne, quel est le temps écoulé entre le début d'un rapport et de sa fin ?

<br>

In [32]:
# This block calculates one scalar value: the average elapsed time in days.
temps_moyen_jours = (
    data
    .filter(
        pl.col("cmplnt_fr_dt").is_not_null()
        & pl.col("cmplnt_to_dt").is_not_null()
    )
    .with_columns(
        (pl.col("cmplnt_to_dt") - pl.col("cmplnt_fr_dt")).alias("temps_ecoule")
    )
    .filter(
        pl.col("temps_ecoule").dt.total_seconds() >= 0
    )
    .select(
        (pl.col("temps_ecoule").dt.total_seconds().mean() / 86400)
        .round(2)
        .alias("temps_moyen_jours")
    )
    .collect()
    .item()
)

temps_moyen_jours

15.14

#### 13 Est-ce que ce temps moyen est similaire entre les différents quartiers ? Triez par ordre décroissant et afficher également le nombre d'offenses recensées.

<br>

In [33]:
# This block calculates the average elapsed time by borough
# and counts the number of offenses in each borough.
temps_moyen_par_quartier = (
    data
    .filter(
        pl.col("boro_nm").is_not_null()
        & pl.col("cmplnt_fr_dt").is_not_null()
        & pl.col("cmplnt_to_dt").is_not_null()
    )
    .with_columns(
        (pl.col("cmplnt_to_dt") - pl.col("cmplnt_fr_dt")).alias("temps_ecoule")
    )
    .filter(
        pl.col("temps_ecoule").dt.total_seconds() >= 0
    )
    .group_by("boro_nm")
    .agg(
        pl.len().alias("nombre_offenses"),
        (
            pl.col("temps_ecoule").dt.total_seconds().mean() / 86400
        )
        .round(2)
        .alias("temps_moyen_jours")
    )
    .sort("temps_moyen_jours", descending=True)
    .collect()
)

temps_moyen_par_quartier

shape: (5, 3)
┌───────────────┬─────────────────┬───────────────────┐
│ boro_nm       ┆ nombre_offenses ┆ temps_moyen_jours │
│ ---           ┆ ---             ┆ ---               │
│ str           ┆ u32             ┆ f64               │
╞═══════════════╪═════════════════╪═══════════════════╡
│ QUEENS        ┆ 1436397         ┆ 18.32             │
│ BROOKLYN      ┆ 2001856         ┆ 15.53             │
│ MANHATTAN     ┆ 1584031         ┆ 13.81             │
│ BRONX         ┆ 1253403         ┆ 13.33             │
│ STATEN ISLAND ┆ 292514          ┆ 11.96             │
└───────────────┴─────────────────┴───────────────────┘

#### 14 Affichez par année et ce depuis 2010 la somme cumulée du nombre d'offenses de catégorie *Felony*

**BONUS**: Pouvez-vous constater une accélération ?

<br>

In [34]:
felony_cumulative_by_year = (
    data
    .filter(
         pl.col("cmplnt_fr_dt").is_not_null()
        & pl.col("law_cat_cd").is_not_null()

    )
    .with_columns(
        pl.col("cmplnt_fr_dt").dt.year().alias("annee")
        )
        .filter(
        (pl.col("annee") >= 2010)
        & (pl.col("law_cat_cd") == "FELONY")
        ).group_by("annee")
        .agg(
            pl.len().alias("nombre_offenses")
        )
        .sort("annee")
        .with_columns(
            pl.col("nombre_offenses").cum_sum().alias("somme_cumulee_offenses")
        ).collect()

    )

In [35]:

felony_cumulative_by_year

shape: (13, 3)
┌───────┬─────────────────┬────────────────────────┐
│ annee ┆ nombre_offenses ┆ somme_cumulee_offenses │
│ ---   ┆ ---             ┆ ---                    │
│ i32   ┆ u32             ┆ u32                    │
╞═══════╪═════════════════╪════════════════════════╡
│ 2010  ┆ 147347          ┆ 147347                 │
│ 2011  ┆ 148015          ┆ 295362                 │
│ 2012  ┆ 153848          ┆ 449210                 │
│ 2013  ┆ 154155          ┆ 603365                 │
│ 2014  ┆ 151569          ┆ 754934                 │
│ …     ┆ …               ┆ …                      │
│ 2018  ┆ 140756          ┆ 1338502                │
│ 2019  ┆ 142041          ┆ 1480543                │
│ 2020  ┆ 135126          ┆ 1615669                │
│ 2021  ┆ 148913          ┆ 1764582                │
│ 2022  ┆ 172918          ┆ 1937500                │
└───────┴─────────────────┴────────────────────────┘

In [36]:
data.with_columns(
    pct_change_over_year = pl.nombre_offenses
)

AttributeError: module 'polars' has no attribute 'nombre_offenses'

In [ ]:
# This block adds yearly variation and percentage variation
# to check whether Felony offenses are accelerating or slowing down.
felony_acceleration = (
    felony_cumulative_by_year
    .with_columns(
        pl.col("nombre_offenses").cast(pl.Int64)
         )
         .with_columns(
             (
                 pl.col("nombre_offenses") - pl.col("nombre_offenses").shift(1)
         ).alias("variation_annuelle")
         )
         .with_columns(
             (    
                pl.col("variation_annuelle")
                 / pl.col("nombre_offenses").shift(1)
                * 100
        )
        .round(2)
        .alias("variation_pourcentage")
    ).with_columns(
        pl.col("variation_pourcentage")
        .fill_null(0)
        .cum_sum()
        .round(2)
        .alias("somme_variation_pourcentage")
    )
)

felony_acceleration

shape: (13, 6)
┌───────┬─────────────────┬──────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ annee ┆ nombre_offenses ┆ somme_cumulee_of ┆ variation_annue ┆ variation_pourc ┆ somme_variation │
│ ---   ┆ ---             ┆ fenses           ┆ lle             ┆ entage          ┆ _pourcentage    │
│ i32   ┆ i64             ┆ ---              ┆ ---             ┆ ---             ┆ ---             │
│       ┆                 ┆ u32              ┆ i64             ┆ f64             ┆ f64             │
╞═══════╪═════════════════╪══════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ 2010  ┆ 147347          ┆ 147347           ┆ null            ┆ null            ┆ 0.0             │
│ 2011  ┆ 148015          ┆ 295362           ┆ 668             ┆ 0.45            ┆ 0.45            │
│ 2012  ┆ 153848          ┆ 449210           ┆ 5833            ┆ 3.94            ┆ 4.39            │
│ 2013  ┆ 154155          ┆ 603365           ┆ 307             ┆ 0.2             ┆ 4.59            │
│ 2014  ┆ 151569          ┆ 754934           ┆ -2586           ┆ -1.68           ┆ 2.91            │
│ …     ┆ …               ┆ …                ┆ …               ┆ …               ┆ …               │
│ 2018  ┆ 140756          ┆ 1338502          ┆ -1653           ┆ -1.16           ┆ -4.36           │
│ 2019  ┆ 142041          ┆ 1480543          ┆ 1285            ┆ 0.91            ┆ -3.45           │
│ 2020  ┆ 135126          ┆ 1615669          ┆ -6915           ┆ -4.87           ┆ -8.32           │
│ 2021  ┆ 148913          ┆ 1764582          ┆ 13787           ┆ 10.2            ┆ 1.88            │
│ 2022  ┆ 172918          ┆ 1937500          ┆ 24005           ┆ 16.12           ┆ 18.0            │
└───────┴─────────────────┴──────────────────┴─────────────────┴─────────────────┴─────────────────┘

In [ ]:
# This block calculates acceleration as the change in annual variation.
felony_acceleration = (
    felony_acceleration
    .with_columns(
        (
            pl.col("variation_annuelle") - pl.col("variation_annuelle").shift(1)
        ).alias("acceleration_annuelle")
    )
)

felony_acceleration

shape: (13, 7)
┌───────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ annee ┆ nombre_offens ┆ somme_cumule ┆ variation_an ┆ variation_po ┆ somme_variat ┆ acceleration │
│ ---   ┆ es            ┆ e_offenses   ┆ nuelle       ┆ urcentage    ┆ ion_pourcent ┆ _annuelle    │
│ i32   ┆ ---           ┆ ---          ┆ ---          ┆ ---          ┆ age          ┆ ---          │
│       ┆ i64           ┆ u32          ┆ i64          ┆ f64          ┆ ---          ┆ i64          │
│       ┆               ┆              ┆              ┆              ┆ f64          ┆              │
╞═══════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 2010  ┆ 147347        ┆ 147347       ┆ null         ┆ null         ┆ 0.0          ┆ null         │
│ 2011  ┆ 148015        ┆ 295362       ┆ 668          ┆ 0.45         ┆ 0.45         ┆ null         │
│ 2012  ┆ 153848        ┆ 449210       ┆ 5833         ┆ 3.94         ┆ 4.39         ┆ 5165         │
│ 2013  ┆ 154155        ┆ 603365       ┆ 307          ┆ 0.2          ┆ 4.59         ┆ -5526        │
│ 2014  ┆ 151569        ┆ 754934       ┆ -2586        ┆ -1.68        ┆ 2.91         ┆ -2893        │
│ …     ┆ …             ┆ …            ┆ …            ┆ …            ┆ …            ┆ …            │
│ 2018  ┆ 140756        ┆ 1338502      ┆ -1653        ┆ -1.16        ┆ -4.36        ┆ 5525         │
│ 2019  ┆ 142041        ┆ 1480543      ┆ 1285         ┆ 0.91         ┆ -3.45        ┆ 2938         │
│ 2020  ┆ 135126        ┆ 1615669      ┆ -6915        ┆ -4.87        ┆ -8.32        ┆ -8200        │
│ 2021  ┆ 148913        ┆ 1764582      ┆ 13787        ┆ 10.2         ┆ 1.88         ┆ 20702        │
│ 2022  ┆ 172918        ┆ 1937500      ┆ 24005        ┆ 16.12        ┆ 18.0         ┆ 10218        │
└───────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

#### 15 Affichez toutes les valeurs uniques présentes dans la colonne 'ofns_desc' ainsi que leur nombre d'occurences

**BONUS:** Trouvez une solution afin d'afficher le résultat dans deux colonnes distinctes et triez par ordre décroissant sur le nombre d'occurences

<br>

In [ ]:
data.select(
    "ofns_desc"
).head(5).collect()

shape: (5, 1)
┌────────────────────────────────┐
│ ofns_desc                      │
│ ---                            │
│ str                            │
╞════════════════════════════════╡
│ RAPE                           │
│ GRAND LARCENY OF MOTOR VEHICLE │
│ UNAUTHORIZED USE OF A VEHICLE  │
│ MISCELLANEOUS PENAL LAW        │
│ GRAND LARCENY                  │
└────────────────────────────────┘

In [ ]:
valeurs_uniques_ofns_desc = (
    data.
    select("ofns_desc")
    .unique()
    .collect()
)

valeurs_uniques_ofns_desc

shape: (73, 1)
┌────────────────────────────────┐
│ ofns_desc                      │
│ ---                            │
│ str                            │
╞════════════════════════════════╡
│ OTHER STATE LAWS (NON PENAL LA │
│ CRIMINAL MISCHIEF & RELATED OF │
│ LOITERING/DEVIATE SEX          │
│ LOITERING/GAMBLING (CARDS, DIC │
│ SEX CRIMES                     │
│ …                              │
│ DANGEROUS WEAPONS              │
│ null                           │
│ RAPE                           │
│ LOITERING FOR DRUG PURPOSES    │
│ DISORDERLY CONDUCT             │
└────────────────────────────────┘

In [ ]:
# This block groups rows by offense description
# and counts how many times each offense description appears.
occurances_ofns = (
    data.filter(pl.col("ofns_desc").is_not_null()
                )
                .group_by("ofns_desc")
    .agg(pl.len().alias("nombre_occurences")
    ).sort("nombre_occurences", descending=True)
    .collect()
)

occurances_ofns

shape: (72, 2)
┌─────────────────────────────────┬───────────────────┐
│ ofns_desc                       ┆ nombre_occurences │
│ ---                             ┆ ---               │
│ str                             ┆ u32               │
╞═════════════════════════════════╪═══════════════════╡
│ PETIT LARCENY                   ┆ 1446716           │
│ HARRASSMENT 2                   ┆ 1103353           │
│ ASSAULT 3 & RELATED OFFENSES    ┆ 876955            │
│ CRIMINAL MISCHIEF & RELATED OF  ┆ 834295            │
│ GRAND LARCENY                   ┆ 732709            │
│ …                               ┆ …                 │
│ FORTUNE TELLING                 ┆ 12                │
│ ABORTION                        ┆ 7                 │
│ OFFENSES AGAINST MARRIAGE UNCL  ┆ 5                 │
│ UNDER THE INFLUENCE OF DRUGS    ┆ 3                 │
│ KIDNAPPING AND RELATED OFFENSE… ┆ 3                 │
└─────────────────────────────────┴───────────────────┘

#### 16 Quel est le top 5 des offenses les plus recensées en 2020

<br>

In [ ]:
select.

In [ ]:
top_5_2020 = (
    data.select(
        "ofns_desc","cmplnt_fr_dt"
    ).with_columns(
            pl.col("cmplnt_fr_dt").dt.year().alias("annee")
            )
    .filter(
            (pl.col("annee") == 2020)
    )
    .group_by("ofns_desc"
              )
              .agg(pl.len().alias("nombre_occurences")
                   )
        .sort("nombre_occurences", descending=True
              )
              .head(5).collect()

)

top_5_2020

shape: (5, 2)
┌────────────────────────────────┬───────────────────┐
│ ofns_desc                      ┆ nombre_occurences │
│ ---                            ┆ ---               │
│ str                            ┆ u32               │
╞════════════════════════════════╪═══════════════════╡
│ PETIT LARCENY                  ┆ 82333             │
│ HARRASSMENT 2                  ┆ 66735             │
│ CRIMINAL MISCHIEF & RELATED OF ┆ 47289             │
│ ASSAULT 3 & RELATED OFFENSES   ┆ 43417             │
│ GRAND LARCENY                  ┆ 35573             │
└────────────────────────────────┴───────────────────┘

In [ ]:
top_5_2020 = (
    data.select(
        "ofns_desc","cmplnt_fr_dt"
    ).with_columns(
            pl.col("cmplnt_fr_dt").dt.year().alias("annee")
            )
    .filter(
            (pl.col("annee") == 2020)
            & pl.col("ofns_desc").is_not_null()
    )
    .group_by("ofns_desc"
              )
              .agg(pl.len().alias("nombre_occurences")
                   )
        .sort("nombre_occurences", descending=True
              )
              .head(5).collect()

)

top_5_2020

shape: (5, 2)
┌────────────────────────────────┬───────────────────┐
│ ofns_desc                      ┆ nombre_occurences │
│ ---                            ┆ ---               │
│ str                            ┆ u32               │
╞════════════════════════════════╪═══════════════════╡
│ PETIT LARCENY                  ┆ 82333             │
│ HARRASSMENT 2                  ┆ 66735             │
│ CRIMINAL MISCHIEF & RELATED OF ┆ 47289             │
│ ASSAULT 3 & RELATED OFFENSES   ┆ 43417             │
│ GRAND LARCENY                  ┆ 35573             │
└────────────────────────────────┴───────────────────┘

In [ ]:

#context manager
with pl.Config() as cfg:
    cfg.set_tbl_rows(20)

    tmp = data.select(
        pl.col('ofns_desc').value_counts(normalize=True)
        
    ).unnest().sort("proportion", descending=True).collect()
    display(tmp)

tmp

shape: (73, 2)
┌─────────────────────────────────┬────────────┐
│ ofns_desc                       ┆ proportion │
│ ---                             ┆ ---        │
│ str                             ┆ f64        │
╞═════════════════════════════════╪════════════╡
│ PETIT LARCENY                   ┆ 0.173196   │
│ HARRASSMENT 2                   ┆ 0.13209    │
│ ASSAULT 3 & RELATED OFFENSES    ┆ 0.104986   │
│ CRIMINAL MISCHIEF & RELATED OF  ┆ 0.099879   │
│ GRAND LARCENY                   ┆ 0.087718   │
│ DANGEROUS DRUGS                 ┆ 0.053091   │
│ OFF. AGNST PUB ORD SENSBLTY &   ┆ 0.050153   │
│ FELONY ASSAULT                  ┆ 0.040218   │
│ ROBBERY                         ┆ 0.03567    │
│ BURGLARY                        ┆ 0.033922   │
│ …                               ┆ …          │
│ LOITERING FOR DRUG PURPOSES     ┆ 0.000003   │
│ ADMINISTRATIVE CODES            ┆ 0.000002   │
│ LOITERING/DEVIATE SEX           ┆ 0.000002   │
│ OTHER TRAFFIC INFRACTION        ┆ 0.000002   │
│ OTHER STATE LAWS (NON PENAL LA… ┆ 0.000002   │
│ FORTUNE TELLING                 ┆ 0.000001   │
│ ABORTION                        ┆ 8.3802e-7  │
│ OFFENSES AGAINST MARRIAGE UNCL  ┆ 5.9858e-7  │
│ KIDNAPPING AND RELATED OFFENSE… ┆ 3.5915e-7  │
│ UNDER THE INFLUENCE OF DRUGS    ┆ 3.5915e-7  │
└─────────────────────────────────┴────────────┘

shape: (73, 2)
┌─────────────────────────────────┬────────────┐
│ ofns_desc                       ┆ proportion │
│ ---                             ┆ ---        │
│ str                             ┆ f64        │
╞═════════════════════════════════╪════════════╡
│ PETIT LARCENY                   ┆ 0.173196   │
│ HARRASSMENT 2                   ┆ 0.13209    │
│ ASSAULT 3 & RELATED OFFENSES    ┆ 0.104986   │
│ CRIMINAL MISCHIEF & RELATED OF  ┆ 0.099879   │
│ GRAND LARCENY                   ┆ 0.087718   │
│ …                               ┆ …          │
│ FORTUNE TELLING                 ┆ 0.000001   │
│ ABORTION                        ┆ 8.3802e-7  │
│ OFFENSES AGAINST MARRIAGE UNCL  ┆ 5.9858e-7  │
│ KIDNAPPING AND RELATED OFFENSE… ┆ 3.5915e-7  │
│ UNDER THE INFLUENCE OF DRUGS    ┆ 3.5915e-7  │
└─────────────────────────────────┴────────────┘

#### 17 Parmi ce top 5, quels sont les tranches d'âge les plus touchées en 2020 ?

<br>

In [ ]:
top_5 = data.filter(
    pl.col('cmplnt_fr_dt').dt.year() == 2000
).select(
    pl.col('ofns_desc').value_counts()
).unnest().top_k(5, by='count').collect()

top_5

shape: (5, 2)
┌───────────────┬───────┐
│ ofns_desc     ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ GRAND LARCENY ┆ 202   │
│ SEX CRIMES    ┆ 159   │
│ THEFT-FRAUD   ┆ 134   │
│ PETIT LARCENY ┆ 101   │
│ HARRASSMENT 2 ┆ 76    │
└───────────────┴───────┘

In [ ]:
top_5.get_column(ofns)

#### 18 Afficher l'évolution(en valeur absolue et en %), d'année en année, du nombre d'offenses faites aux femmes depuis 2010

<br>

#### 19 Affichez le nombre d'enregistrements par jour de la semaine(*e.g.* lundi, mardi, *etc.*) et ce pour Manhattan

<br>

#### 20 Ajoutez une colonne aux données qui doit permettre d'identifier des moments dans les journées en fonction de l'heure

*e.g.*:
- entre 22h00 et 04h59 => NIGHT
- entre 05H00 et 18h59 => DAY
- entre 19h00 et 21h59 => EVENING

Ensuite afficher le nombre d'enregistements par période et par type d'infraction(*i.e.* law_cat_cd)

<br>

#### 21 Afin de pouvoir trier correctement le résultat de l'exercice précédent, ajoutez une colonne reprenenant le niveau de gravité:

- 1: 'FELONY'
- 2: 'MISDEMEANOR'
- 3: 'VIOLATION'

#### 22 Reprenez l'exercice précédent mais en ne gardant que les cinq dernières années disponnibles et en excluant les infractions les plus minimes

<br>

#### 23 Proposez un crosstab avec le nombre d'enregistrements par type d'infractions et moment de la journée

Plusieurs remarques:
- nous voudrions également avoir non pas les valeurs absolues mais les ratios. Ces ratios peuvent être calculer de trois façons:
    - en divisant chaque cellule par la somme de sa colonne
    - en divisant chaque cellule par la somme de sa ligne
    - en divisant chaque cellule par le total de la matrice
- l'exercice est plus facile à réaliser si vous passez par Pandas qui propose une solution avec crosstab. Nous voudrions que vous proposiez également une solution sans passer par Pandas.

<br>

#### 24 Identifiez les offenses qui ont connu, en moyenne, la plus grande progression sur les 10 dernières années disponnibles

**Compléments d'informations**: nous voulons pour chaque offense et pour chaque année avoir son nombre d'occurences et afficher sa progression par rapport à n-1 et ensuite faire une moyenne sur ces progressions.

<br>

#### 25 Filtrez afin de ne garder que les offenses avec au minimum 1000 enregistrements

##### 25.1 Affichez également le top et bottom 10

<br>

#### 26 A l'aide d'une fenêtre, identifiez les moments dans la journée et dans l'année qui répertorient le plus de plaintes

<br>

#### 26.1 Pouvez-vous constater une différence entre les différentes gravités de crimes ? Certains crimes ont-ils tendance a plus être commis à telle ou telle heure de la journée ?

<br>

#### 27 Et quelle est la période dans l'année la plus propice ?

<br>